Multimat dgp1
quinoacomputing/quinoa pull request #439
Opened 2020-08-05 20:39 UTC by WeizhaoLi2018

Implement DGP1 for Multi-Material scheme.

2020-08-05 20:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/quinoacomputing/quinoa?pullRequest=439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/quinoacomputing/quinoa?pullRequest=439) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/quinoacomputing/quinoa?pullRequest=439) it.</sub>

2020-10-28 01:04 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 3 of 28 files reviewed, 28 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MKgWocT0Rl0_XCnkOWu:byh1onq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

It is always symmetric matrix since what we really solve is A^T * A * x = A^T * b, and matrix A^T * A is symmetric.
I will change the code to use Cholesky to solve the linear system.
</blockquote></details>

I think we could first merge the current code and improve this linear system solver in next PR.
___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MKfbqNd-jzuAtZqmFmQ:b-1tozvp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Okay, then I suspect we could use 1e-14 or 1e-16, since beyond that double precision floats loose their precision.
</blockquote></details>

Just changed it to 1e-16.
___
*[src/PDE/Limiter.cpp, line 859 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc547n1U4yGsfKbwnN:-MKfc3iW-mYMRRqsB8mE:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L859)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

We don't seem to write to `U` below. If so, let's make it `const`.
</blockquote></details>

Done.
___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MKgZ8XvCqYTawJ65rtN:b-s2b05h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why don't/can't we use here `tk::lpofa`, defined in `Mesh/DerivedData.hpp`?
</blockquote></details>

I am not aware of the data tk::lpofa. Is it generated from Mesh/DerivedData.cpp?
___
*[src/PDE/Limiter.cpp, line 947 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF12_i5ArxSM8ejheF0:-MKfcxqaCMorEbvQj4l5:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L947)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you replace the `fabs()` with `std::fabs()`?
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/DGCompFlow.hpp, line 270 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc6rVxD3FqCTbORfDw:-MKfmnPj3eq9TMVNjdvs:baaxbhp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/CompFlow/DGCompFlow.hpp#L270)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Or define a new function that is only called for multimat, as I suggested earlier.
</blockquote></details>

I did vriem and xcoord the same as riemannDeriv so that we only allocate these variables for multimat.
___
*[src/PDE/Integrate/Boundary.cpp, line 71 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF15PRa-JdO5UNWK3u2:-MKgBG4M7wY0DoDRhoEh:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L71)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Good idea @adityakpandare .
</blockquote></details>

Done.
___
*[src/PDE/Integrate/Boundary.cpp, line 185 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF0wf3p-fTKxa5vTBKs:-MKgBQeC7f2w3pHZZlFx:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L185)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's change the first conditional for this if-test to `nmat > 1` rather than `fl.size() > ncomp`.
</blockquote></details>

Done.
___
*[src/PDE/Integrate/Boundary.cpp, line 193 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF17ryT2pEWa_jNdOAb:-MKgBw14E6ew3O5olsCD:b2e319g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L193)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

`pbl` and `pbr` usually denote bulk pressures. I would suggest a name such as `rhobl` and `rhobr` for bulk densities.
</blockquote></details>

That's a typo. I changed it to rhobl and rhobr. The code is moved to PDE/Integrate/Basis.cpp
Thanks!
___
*[src/PDE/Integrate/Boundary.cpp, line 206 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF14hPv8vciFOlBrn_i:-MKgCZEj7aL15sqWMTxP:b-1yah9y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L206)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why don't we add a `using inciter::momentumIdx` to the beginning of the function? That would avoid the repetitive `inciter::`.
</blockquote></details>

Done. The code is moved to PDE/Integrate/Basis.cpp
___
*[src/PDE/Integrate/Boundary.cpp, line 215 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF1B4ht-ZkiJ6aIczsk:-MKgCaHWDNg-JcZiF2-f:b-1yah9y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L215)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This comment seems misleading. From what I understand, the normal velocity is taken from the Riemann solver (`fl[ncomp+nmat]`) and the *tangential* (not "vertical") velocity is taken as an average of left and right states. Let's update the comment above accordingly.
</blockquote></details>

Done. The code is moved to PDE/Integrate/Basis.cpp
___
*[src/PDE/Integrate/Boundary.cpp, line 223 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc7-xQ4l8NC5e0uZO3:-MKgCjEL2aLGO5JYk2I2:b-3bllw2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L223)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's separate the above in another, separate function and call it for multimat only.
</blockquote></details>

Make it a separate function in Basis.cpp now.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 64 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF1UWyrBxvKNQb2zW2h:-MKgD5Sl4bnjlEso32fs:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L64)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's call this "Vector of *Riemann* velocity polynomial"
</blockquote></details>

Done.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 174 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF1ZvnA7elGK-eTkF4y:-MKgRU4QAeMMoXXeb27y:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L174)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

These `ncf` calculations should be augmented with the higher-order DOF `ncf` [...]

2020-10-30 19:21 UTC, adityakpandare requested changes
Thanks for implementing this @weizhaoli2018! I have a few comments below. I would suggest going thru the code you've changed and put some comments around places where we usually do.

> Reviewed 28 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MKuwTr-8F5ME3AMOgWC:bvbis6l)* status: all files reviewed, 21 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MKk-PpF1sN7GbT_T9gR:b-lry3bt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I am not aware of the data tk::lpofa. Is it generated from Mesh/DerivedData.cpp?
</blockquote></details>

`tk::lpofa` is stored in `Mesh/DerivedData.hpp`. I think that can be used here.
___
*[src/PDE/Integrate/Basis.cpp, line 375 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuNqa2Azzw7vAevJK2:-MKuNqa37L2Lt2_WBBSc:b-q79fg8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L375)):*
> ```cpp
>                   const std::array< std::vector< tk::real >, 2 >& state,
>                   std::vector< std::vector< tk::real > >& vriem,
>                   std::vector< std::vector< tk::real > >& riemannLoc )
> ```

Let's move this function to `Integrate/MultiMatTerm.cpp`
___
*[src/PDE/Integrate/Basis.cpp, line 430 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKusVoJ7MpKVusFVbIi:-MKusVoJ7MpKVusFVbIj:b-n8hvxi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L430)):*
> ```cpp
>   // The interface velocity is evaluated by adding the normal velocity which
>   // is taken from the Riemann solver and the tangential velocity which is
>   // evaluated as an average of the left and right cells
> ```

Thanks for the comment!
___
*[src/PDE/Integrate/Boundary.cpp, line 71 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF15PRa-JdO5UNWK3u2:-MKk1JrO6kSoCyxe6CkZ:b-9755fn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L71)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!
___
*[src/PDE/Integrate/Boundary.cpp, line 215 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF1B4ht-ZkiJ6aIczsk:-MKk1ikaE4ZoibYaSRfB:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/Boundary.cpp#L215)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done. The code is moved to PDE/Integrate/Basis.cpp
</blockquote></details>

Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 187 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF1UvaGELiY7QbjQVmA:-MKk2HG1E33VahWePUye:b-g6llew) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L187)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

It is ndof for the Riemann velocity polynomial. The reason I didn't use ndof is that in the future if we implement DGP2, the ndof of the Riemann velocity polynomial will still remain as 4 while ndof from the system is 10.
</blockquote></details>

Makes sense. Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 445 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcBEyJ04Ocw12xZMKY:-MKk06JL4V94y4rcvtjz:b-4wn5pd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L445)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I believe the for-loop is still not correct. The upper limit to `idof` should be `idof<ndof_el`, so that it works for p-adaptation.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 503 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MF0ymT_1rUGEfGwzC8I:-MKk0f1815hDDdiLkprz:b-wtkc5u) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L503)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I rename it to AA_T since it is actually A * A^T. Does this sound good?
</blockquote></details>

Yes, thank you!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MKuu1bm8G5XjYCBvevi:b-9kmmkh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
> ```cpp
>       auto mark = k*ndof;
>       for(std::size_t idof = 1; idof < ndof; idof++)
>         R(e, mark+idof, offset) += wt * ncf[k][idof];
> ```

Why isn't the RHS contribution multiplied by `B[idof]`?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MKutZqJ6Sj8nCxGa97J:b-u1nqzr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
> ```cpp
>     }
> 
>     for (ncomp_t c=nmat; c<ncomp; ++c)
> ```

Why does `c` begin with `nmat`? I can see the loop you've separated above this; why are these two loops separate? Let's combine both of these so that `c` can go from `0` to `ncomp-1`.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 167 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuvfKbAQT117JSJ2G-:-MKuvfKbAQT117JSJ2G0:bmy71cj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/MultiMat/DGMultiMat.hpp#L167)):*
> ```cpp
> 
>         tk::GaussQuadratureTet( ng, coordgp, wgp );
> ```

Let's comment here that this loop is over quadrature points in element `e`.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 178 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuvBDc4Zaoqs0PRXGQ:-MKuvBDc4Zaoqs0PRXGR:b-tz5fm8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/MultiMat/DGMultiMat.hpp#L178)):*
> ```cpp
>           auto state = tk::eval_state( 3*nmat+3, 0, rdof, ndof, e, unk, B );
> 
>           // cell-average bulk density
> ```

This is not cell-averaged bulk density anymore. Let's update this comment to "bulk density at quadrature point".
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 183 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuv0UT15RLMs8WjO9I:-MKuv0UT15RLMs8WjO9J:b-wgi0cq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/MultiMat/DGMultiMat.hpp#L183)):*
> ```cpp
>             rhob += state[densityIdx(nmat, k)];
> 
>           // cell-average velocity
> ```

This is not cell-averaged velocity anymore. Let's update this comment to "velocity at quadrature point".
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 189 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuvRb-DYVU9PovpmwC:-MKuvRb-DYVU9PovpmwD:br7nntl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/MultiMat/DGMultiMat.hpp#L189)):*
> ```cpp
>                  state[momentumIdx(nmat, 2)]/rhob };
> 
>           std::vector< tk::real > pri(nmat + 3, 0.0);
> ```

Let's put in a comment here which explains that the forthcoming loop computes the material pressure at this quadrature point.
___
*[src/PDE/MultiMat/DGM [...]

2020-10-30 20:23 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 21 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MKv947D4aLcOJoYI-4N:bxoo2j5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why isn't the RHS contribution multiplied by `B[idof]`?
</blockquote></details>

The reason is the differences in the non-conservative terms for volume fraction equations and other equations.
For volume fraction equations, it is in a form of
    ( \partial (u * B)) / (\partial x) = u * (\partial B) / (\partial x) + u *(\partial u) / (\partial x)
However, for others, it is simply s * B_i.
That is also the reason why there are two loops. This one is for evaluating the non-conservative form for volume fractions. And the next one is for other equations so the counter in the next loop starts with nmat.

Let me know if you still have questions. I will add comments for this in the code.
___
*[tests/regression/inciter/compflow/Euler/SodShocktube/rotated_sod_shocktube_dg.std.exo, line  at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKk2lJ7AB1Xwu13uubb:-MKv8TzD3stBaGWNvAF3:b-7h82l7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/tests/regression/inciter/compflow/Euler/SodShocktube/rotated_sod_shocktube_dg.std.exo#L)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why were the single-material shocktube baselines changed in this commit?
</blockquote></details>

Because we changed the hard limiter from 1o-20 to 1e-16 and it cause some minor differences in binary outputs. And you can see that the diag file do not differ.


<!-- Sent from Reviewable.io -->

2020-10-30 20:24 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 21 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MKvAW-CBheEwKCa9Yvb:beggkws) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

The reason is the differences in the non-conservative terms for volume fraction equations and other equations.
For volume fraction equations, it is in a form of
    ( \partial (u * B)) / (\partial x) = u * (\partial B) / (\partial x) + u *(\partial u) / (\partial x)
However, for others, it is simply s * B_i.
That is also the reason why there are two loops. This one is for evaluating the non-conservative form for volume fractions. And the next one is for other equations so the counter in the next loop starts with nmat.

Let me know if you still have questions. I will add comments for this in the code.
</blockquote></details>

Sorry, the equation should be
    ( \partial (u * B)) / (\partial x) = u * (\partial B) / (\partial x) + B * (\partial u) / (\partial x)
I have a typo for the last term.


<!-- Sent from Reviewable.io -->

2020-11-02 16:25 UTC, jbakosi requested changes
> Reviewed 28 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 18 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-ML8aMbo54rny2HuNb0z:b3ojscr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I think we could first merge the current code and improve this linear system solver in next PR.
</blockquote></details>

I think if we do not hook up LAPACK/MKL here now, this will slip and we will not do it. It is really very simple, see
`DiffEq/OrnsteinUhlenbeck/OrnsteinUhlenbeck.hpp` as an example for how to include LAPACK/MKL and how to do a Cholesky decomposition on `m_sigma` in place.

In addition, if you had use LAPACK/MKL since beginning, you would not have had to fix the problem with testing for positivity of `i`, an unsigned integer.

Also, if the solver here in `tk::LU` is for a symmetric solver, we should not call it `LU`. Also, if a library is called, this whole function is not even needed: just call the library at the call site.
___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-ML8buVW-ZpjcWS29_62:b4avfrs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just changed it to 1e-16.
</blockquote></details>

I'm still puzzled by this: Testing any positive double-precision floating point number to see if it is lower than 1e-16 makes no sense, see https://en.wikipedia.org/wiki/Machine_epsilon. If it is less than 2.22e-16, it was already zero for practical purposes. If that if test is not there, does it really affect the regression test results?
___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-ML8coEB3OC2xsm1AYtD:b-j3pgvk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

`tk::lpofa` is stored in `Mesh/DerivedData.hpp`. I think that can be used here.
</blockquote></details>

It is not _generated_. Is simply declared to define a node ordering convention. It is used at other places in the code and I think it would be prudent to not invent a new one here but use that convention.
___
*[src/PDE/Integrate/Basis.cpp, line 377 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8e6JH5q64xqQTF8wz:-ML8e6JH5q64xqQTF8x-:bgiuw2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L377)):*
> ```cpp
>                   std::vector< std::vector< tk::real > >& riemannLoc )
> // *****************************************************************************
> //  Compute the riemann velociry at the interface
> ```

velocity
___
*[src/PDE/Integrate/Basis.cpp, line 397 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8eBbT43WpXgsb84Y6:-ML8eBbT43WpXgsb84Y7:b-ujbckq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L397)):*
> ```cpp
>   if(e_right != -1)
>     er = static_cast< std::size_t >(e_right);
>   
> ```

extra white spaces above
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 454 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcBca6-ScVQzB5zAmZ:-ML8ghNw5wPyjEJl-7tp:by9g2gk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L454)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just changed it to passing value by reference.
</blockquote></details>

You don't modify `nelem` inside the function and `std::size_t` is not large. I would pass it by value:
```
void solvevriem( std::size_t nelem,
```
This way, the compiler makes a copy of `nelem`, which is likely be a local copy on the stack and thus addressable by a shorter pointer (in assembly code) than having to generate code to reach back into the call site with it (using a 64-bit pointer), so it is shorter, simpler code, and potentially more efficient.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 457 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcAMgW6ycezrOL1qwn:-ML8hkVT0hYcbmD2gX4j:bea0n35) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L457)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I didn't make it return-style because the data vriempoly is defined in DGMultiMat.cpp and is passed to the function nonConservativeInt so that the function solvevriem only modifies the data.
</blockquote></details>

That's fine, but you can still write it the following way, which I think is cleaner:

In `dg::MultiMat::rhs()`
```
      auto virempoly = tk::solvevriem(nelem, vriem, riemannLoc, vriempoly);

      // compute volume integrals of non-conservative terms
      tk::nonConservativeInt( m_system, nmat, m_offset, ndof, rdof, nelem,
                              inpoel, coord, geoElem, U, P, riemannDeriv,
                              vriempoly, ndofel, R );
```
and then `solvevriem()` would look like this:
```
std::vector< std::vector< tk::real > >
solvevriem( ... ) {
    std::vector< std::vector< tk::real > >
      vriempoly( U.nunk(), std::vector<tk::real>(12,0.0) );
     ...
    return vriempoly;
}
```

This is better because
1. It explicitly expresses the _intent_ that `vriempoly` is intended to be _created_ by `solvevriem()` and not just modified, and
2. It hides the complexity of the type of `vriempoly` at the call site. (If someone is reading the call site, it is likely that they don't care about the type of `vriempoly` only the code-flow in which `vriempoly` is created immediately above the call to `nonConservativeInt()`, which then consumes it.)
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 207 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8f-lA4FDyquqWyvKt:-ML8f-lBEnJ9HxInlN5R:b-evlrqf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L207)):*
> ```cpp
> 
> void
> update_rhs_ncn(
> ```

Can we call this instead `updateRhsNonCons()`? I think that is easier to read and understand. @adityakpandare: what do you think?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-ML8fhO-El1fucoftozz:bkmp8em) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why does `c` begin with `nmat`? I can see the loop you've separated above this; why are these two loops separate? Let's combine both of these so that `c` can go from `0` to `ncomp-1`.
</blockquote></details>

I think this is confusing. Is this update function used for both single and multimat? It seems like it. If that's the case we should put the code into two separate functions, one for single and one for multimat.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 225 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8l25iEQBNl3n0TvJc:-ML8l25iEQBNl3n0TvJd:bmm44hk) ([raw file](https://github.com/quinoacomputing/quinoa/bl [...]

2020-11-05 23:35 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 22 of 30 files reviewed, 18 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MLPVf2WB9DgRQdrtfcH:bx8ncpj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I'm still puzzled by this: Testing any positive double-precision floating point number to see if it is lower than 1e-16 makes no sense, see https://en.wikipedia.org/wiki/Machine_epsilon. If it is less than 2.22e-16, it was already zero for practical purposes. If that if test is not there, does it really affect the regression test results?
</blockquote></details>

First, it do affect a few regression test results with or without this hard limiter. And all the results affected are shocktube problems. So all of them are 1D problem setup. So I suppose the differences are caused by the variables for y or z direction, which should be almost zero. But they may end up different magnitudes.
Second, the reason I put it here is that we will encounter an underflow issue caused by some z-direction variables with really small magnitude for DGP1 MultiMat.
___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MKv6otv1cpjUaVASdtz:b1as9he) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

It is not _generated_. Is simply declared to define a node ordering convention. It is used at other places in the code and I think it would be prudent to not invent a new one here but use that convention.
</blockquote></details>

Just changed it to `lpofa`.
And all the sodshocktube regression testcases pass. But for water-air shocktube, the diagnostic file pass while the binary does not pass. I run it until the final time for water-air shocktube, overall it is consistent with my previous P1 results while shows slightly different at the shock side.
The differences between my previous code and with `lpofa` is actually the sequence of the node index.
For example, for one face, previous code shows index as `inpoel[4*e ], inpoel[4*e+1], inpoel[4*e+2]` while with `lpofa` it will be `inpoel[4*e ], inpoel[4*e+2], inpoel[4*e+1]`. In theory, this should not affect the gauss point evaluation and related results as the regression tests of sodshocktube shows. But it seems this cause slightly different to water-air shocktube even though not huge different since diagnostic file pass.
That's the reason I update the binary result of water-air shocktube regression test.
___
*[src/PDE/Integrate/Basis.cpp, line 375 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuNqa2Azzw7vAevJK2:-MLLZA_u0szVbIxTQMYI:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L375)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's move this function to `Integrate/MultiMatTerm.cpp`
</blockquote></details>

Done.
___
*[src/PDE/Integrate/Basis.cpp, line 377 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8e6JH5q64xqQTF8wz:-MLLZ7HCB2P9ABVVirD9:b-1jl013) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L377)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

velocity
</blockquote></details>

Fixed. Thank you!
___
*[src/PDE/Integrate/Basis.cpp, line 397 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8eBbT43WpXgsb84Y6:-MLLZ9HO4Tu5H8Qqf7tg:bss4a2b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/Basis.cpp#L397)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

extra white spaces above
</blockquote></details>

Removed.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 445 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcBEyJ04Ocw12xZMKY:-MLG75uI0TSxpQDCqnTZ:b-6ougq2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L445)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I believe the for-loop is still not correct. The upper limit to `idof` should be `idof<ndof_el`, so that it works for p-adaptation.
</blockquote></details>

I wrote this as ndof instead of ndof_el because if DGP0P1 is applied, ndof_el will be 4 instead of 1.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 454 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcBca6-ScVQzB5zAmZ:-MLG84MQD01HQqa7TCJN:b-4w5kb9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L454)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

You don't modify `nelem` inside the function and `std::size_t` is not large. I would pass it by value:
```
void solvevriem( std::size_t nelem,
```
This way, the compiler makes a copy of `nelem`, which is likely be a local copy on the stack and thus addressable by a shorter pointer (in assembly code) than having to generate code to reach back into the call site with it (using a 64-bit pointer), so it is shorter, simpler code, and potentially more efficient.
</blockquote></details>

Oh, sorry, I think I mistake your previous comment. Just remove the const and pass it by value.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 457 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcAMgW6ycezrOL1qwn:-MLLc6y7-gl1NcT8Wd4g:b3bzeix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L457)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

That's fine, but you can still write it the following way, which I think is cleaner:

In `dg::MultiMat::rhs()`
```
      auto virempoly = tk::solvevriem(nelem, vriem, riemannLoc, vriempoly);

      // compute volume integrals of non-conservative terms
      tk::nonConservativeInt( m_system, nmat, m_offset, ndof, rdof, nelem,
                              inpoel, coord, geoElem, U, P, riemannDeriv,
                              vriempoly, ndofel, R );
```
and then `solvevriem()` would look like this:
```
std::vector< std::vector< tk::real > >
solvevriem( ... ) {
    std::vector< std::vector< tk::real > >
      vriempoly( U.nunk(), std::vector<tk::real>(12,0.0) );
     ...
    return vriempoly;
}
```

This is better because
1. It explicitly expresses the _intent_ that `vriempoly` is intended to be _created_ by `solvevriem()` and not just modified, and
2. It hides the complexity of the type of `vriempoly` at the call site. (If someone is reading the call site, it is likely that they don't care about the type of `vriempoly` only the code-flow in which `vriempoly` is created immediately above the call to `nonConservativeInt()`, which then consumes it.)
</blockquote></details>

Got it. Just changed the function to return `vriempoly`.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MLG6h0x1RenotPdtkGn:bp16x2a) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, jbakosi (Jozsef B [...]

2020-11-05 23:44 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 22 of 30 files reviewed, 18 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MLPmFCbE-tFZCZA5HNF:b-wnchql) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I think if we do not hook up LAPACK/MKL here now, this will slip and we will not do it. It is really very simple, see
`DiffEq/OrnsteinUhlenbeck/OrnsteinUhlenbeck.hpp` as an example for how to include LAPACK/MKL and how to do a Cholesky decomposition on `m_sigma` in place.

In addition, if you had use LAPACK/MKL since beginning, you would not have had to fix the problem with testing for positivity of `i`, an unsigned integer.

Also, if the solver here in `tk::LU` is for a symmetric solver, we should not call it `LU`. Also, if a library is called, this whole function is not even needed: just call the library at the call site.

</blockquote></details>

Hi Jozsef, correct me if I am wrong since I am not familiar with LAPACK library.
I check the function `LAPACKE_dpotrf` used in `DiffEq/OrnsteinUhlenbeck/OrnsteinUhlenbeck.hpp`. Just have a question about it, is this function for a matrix to do Cholesky-decomposition or it is a linear system solver using Cholesky-decomposition?


<!-- Sent from Reviewable.io -->

2020-11-06 15:31 UTC, jbakosi requested changes
> Reviewed 8 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 29 of 30 files reviewed, 16 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MLT81fJ2v-4JGJS9xt_:b2l89dt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Hi Jozsef, correct me if I am wrong since I am not familiar with LAPACK library.
I check the function `LAPACKE_dpotrf` used in `DiffEq/OrnsteinUhlenbeck/OrnsteinUhlenbeck.hpp`. Just have a question about it, is this function for a matrix to do Cholesky-decomposition or it is a linear system solver using Cholesky-decomposition?

</blockquote></details>

http://www.netlib.org/lapack/explore-html/d1/d7a/group__double_p_ocomputational_ga2f55f604a6003d03b5cd4a0adcfb74d6.html
___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MLT8KH0AQHWY4exqaMf:beqj7pf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

First, it do affect a few regression test results with or without this hard limiter. And all the results affected are shocktube problems. So all of them are 1D problem setup. So I suppose the differences are caused by the variables for y or z direction, which should be almost zero. But they may end up different magnitudes.
Second, the reason I put it here is that we will encounter an underflow issue caused by some z-direction variables with really small magnitude for DGP1 MultiMat.
</blockquote></details>

I'm not sure what you mean underflow here. If there is a floating point underflow, https://github.com/quinoacomputing/quinoa/blob/develop/src/Base/ProcessException.cpp#L100 will trigger anyway, no need to test for it.


<!-- Sent from Reviewable.io -->

2020-11-06 15:38 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 29 of 30 files reviewed, 16 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MLTBSVx7yBtnviJmHY8:b-t1wqaj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I'm not sure what you mean underflow here. If there is a floating point underflow, https://github.com/quinoacomputing/quinoa/blob/develop/src/Base/ProcessException.cpp#L100 will trigger anyway, no need to test for it.
</blockquote></details>

What I mean is that without this hard limiter, there will be a floating point underflow for MultiMat DGP1. In that case, the error signal will be triggered and the simulation will exit. So I put it here to avoid the underflow.


<!-- Sent from Reviewable.io -->

2020-11-06 15:49 UTC, jbakosi requested changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 29 of 30 files reviewed, 16 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MLTDNfPDDEJLoZzCNo5:bypjprn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

What I mean is that without this hard limiter, there will be a floating point underflow for MultiMat DGP1. In that case, the error signal will be triggered and the simulation will exit. So I put it here to avoid the underflow.
</blockquote></details>

Ah! Okay, that makes it clear. In that case, if you are absolutely sure that you are okay with that floating point value triggering garbage and _you want include that garbage in your results_, the way to ignore it is to tell the compiler to locally ignore that exception:
```
      fenv_t fe;
      feholdexcept( &fe );
      < ... floating point magic here that we ignore if triggers an underflow ... >
      feclearexcept( FE_UNDERFLOW );
      feupdateenv( &fe );
```
Example: https://github.com/quinoacomputing/quinoa/blob/develop/src/RNG/Random123.hpp#L158


<!-- Sent from Reviewable.io -->

2020-11-13 16:38 UTC, adityakpandare requested changes
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 9 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MM1NBpY-DIdpmUYUusH:b-gxoqc4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just changed it to `lpofa`.
And all the sodshocktube regression testcases pass. But for water-air shocktube, the diagnostic file pass while the binary does not pass. I run it until the final time for water-air shocktube, overall it is consistent with my previous P1 results while shows slightly different at the shock side.
The differences between my previous code and with `lpofa` is actually the sequence of the node index.
For example, for one face, previous code shows index as `inpoel[4*e ], inpoel[4*e+1], inpoel[4*e+2]` while with `lpofa` it will be `inpoel[4*e ], inpoel[4*e+2], inpoel[4*e+1]`. In theory, this should not affect the gauss point evaluation and related results as the regression tests of sodshocktube shows. But it seems this cause slightly different to water-air shocktube even though not huge different since diagnostic file pass.
That's the reason I update the binary result of water-air shocktube regression test.
</blockquote></details>

I'm not sure I understand why the effect of the limiter changes if the node ordering is changed. Shouldn't the limiter-operation be "commutative" with node-ordering? Have you checked if the volume-fraction is indeed bounded between \eps and 1-\eps after this limiting?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 445 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEcBEyJ04Ocw12xZMKY:-MM1LzzTCzBbuEMr4Qir:b-vc4to2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Integrate/MultiMatTerms.cpp#L445)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I wrote this as ndof instead of ndof_el because if DGP0P1 is applied, ndof_el will be 4 instead of 1.
</blockquote></details>

Good point. Thanks for the explanation.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 197 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MM1SfiW00JIO5wXoXSH:-MM1SfiW00JIO5wXoXSI:b-ennww4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L197)):*
> ```cpp
>          for(std::size_t idof=1; idof<ndof; ++idof)
>             ncf[volfracIdx(nmat, k)][idof] = ugp[volfracIdx(nmat, k)] *
>               (riemannDeriv[3*nmat][e] * B[idof] + vriem[0] * dBdx[0][idof]
> ```

The first part of the `ncf[volfrac...][idof]`, is equal to `ncf[volfrac...][0]*B[idof]`. Let's do it that way, so that it's easier to understand, and reduces the computation, since it's already computed a few lines above. 
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 207 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8f-lA4FDyquqWyvKt:-MM1LoZy3oUPSGxMLaxW:b-8zk0ar) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L207)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Can we call this instead `updateRhsNonCons()`? I think that is easier to read and understand. @adityakpandare: what do you think?
</blockquote></details>

I agree that would make it easier to read.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MM1PWwf02OUR49DuxJ3:b82ic01) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Sorry, the equation should be
    ( \partial (u * B)) / (\partial x) = u * (\partial B) / (\partial x) + B * (\partial u) / (\partial x)
I have a typo for the last term.
</blockquote></details>

Okay, I understand your point. Now, one thing to note: we do not assume that the first `nmat` equations are volume fraction equations. This is because we want to be able to augment other equations to the system, and change the ordering of equations, and not change the equation indices all over the place. This is why we use the interfaces `volfracIdx()` (from MultiMatIndexing.hpp) to access the index for the volfrac equations. So, the first loop should not be from 0 to nmat, but should use `volfracIdx(nmat,0)` to `volfracIdx(nmat,nmat-1)` to access the correct equation indices. Same comment about the second loop: we will need the loop to be over `energyIdx()`, not nmat to ncomp. Could you please fix this?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MM1T2BC1L1cLIEqfLg5:bf8k4tv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

This is only for multimat. All the code in this file (MultiMatTerms.cpp) are only called when it's multimat.
</blockquote></details>

As I mentioned above, we should change the loop extents to use the `Idx` interfaces.


<!-- Sent from Reviewable.io -->

2020-12-21 22:31 UTC, WeizhaoLi2018 reviewed
Hi guys, I think the last change I need to do in this review is to make sure the matrix solver from lapack is implemented properly. I am using the function `dsysv` from lapack. It is a linear system solver for symmetric matrix and you can find the description in http://www.netlib.org/lapack/explore-html/d6/d0e/group__double_s_ysolve_ga9995c47692c9885ed5d6a6b431686f41.html#ga9995c47692c9885ed5d6a6b431686f41.  The reason that I am not using Cholesky decomposition is that I am not sure whether the matrix here is postive-definite or not.
However, when I added the statement to include lapack library, some compiling errors appear. Could you guys help me to check on that? I will send you my screen output for this error. You can also checkout this branch and did the compilation and will see the error.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MP6KM7X5qoZNLYqizIg:b-k6lhx4)* status: 5 of 32 files reviewed, 10 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MP5tDRI3szteI79YDrl:b-2c0f3d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Ah! Okay, that makes it clear. In that case, if you are absolutely sure that you are okay with that floating point value triggering garbage and _you want include that garbage in your results_, the way to ignore it is to tell the compiler to locally ignore that exception:
```
      fenv_t fe;
      feholdexcept( &fe );
      < ... floating point magic here that we ignore if triggers an underflow ... >
      feclearexcept( FE_UNDERFLOW );
      feupdateenv( &fe );
```
Example: https://github.com/quinoacomputing/quinoa/blob/develop/src/RNG/Random123.hpp#L158
</blockquote></details>

I don't think we should tell the compiler to ignore the underflow here.
The reason is that the simulation will encounter this underflow issue when we called the `eval_state` function without the hard limiter. If we let that function ignore the underflow issue, I think it is not good for us to debug the code for the future development. So I add the hard limiter (the `if` statement in DG.cpp) in order to make sure we only ignore the underflow issue when some high order coefficients of the numerical solutions are close to zero.
___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MP6JbXJ3l__p1biIGTQ:bhq9r0y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I'm not sure I understand why the effect of the limiter changes if the node ordering is changed. Shouldn't the limiter-operation be "commutative" with node-ordering? Have you checked if the volume-fraction is indeed bounded between \eps and 1-\eps after this limiting?
</blockquote></details>

You are right. The limiter should produce the same results no matter the node-ordering. But I haven't figured it out why the water-air shocktube has a diff binary for that.
Also, the previous bound preserving limiter only limits the volume fraction between \eps and 1. So I just change the bound to [\eps, 1-\eps]. You can check the changes below. During the simulation of water-air shocktube testcase, I check the bound of volume fraction after limiting. It is in the range of [\eps, 1-\eps].
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 197 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MM1SfiW00JIO5wXoXSH:-MP5yDFd7a48Mudia7yK:b-ioxi27) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L197)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The first part of the `ncf[volfrac...][idof]`, is equal to `ncf[volfrac...][0]*B[idof]`. Let's do it that way, so that it's easier to understand, and reduces the computation, since it's already computed a few lines above. 
</blockquote></details>

Done. Thank you!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 207 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-ML8f-lA4FDyquqWyvKt:-MP5sii21ErD_WaYuUqD:b-ioxi27) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L207)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I agree that would make it easier to read.
</blockquote></details>

Done. Thank you!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MP5zK4tEuVKrVm44HTS:b-4623wl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Okay, I understand your point. Now, one thing to note: we do not assume that the first `nmat` equations are volume fraction equations. This is because we want to be able to augment other equations to the system, and change the ordering of equations, and not change the equation indices all over the place. This is why we use the interfaces `volfracIdx()` (from MultiMatIndexing.hpp) to access the index for the volfrac equations. So, the first loop should not be from 0 to nmat, but should use `volfracIdx(nmat,0)` to `volfracIdx(nmat,nmat-1)` to access the correct equation indices. Same comment about the second loop: we will need the loop to be over `energyIdx()`, not nmat to ncomp. Could you please fix this?
</blockquote></details>

Done.
Thank you!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MP5zRVZAy9xyWdk8_dz:boyexb3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

As I mentioned above, we should change the loop extents to use the `Idx` interfaces.
</blockquote></details>

Done. Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 494 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MP6Q4vv1u_tQ9cwuVh1:-MP6Q4vv1u_tQ9cwuVh2:bfepe48) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74e5842da5ae1c41a11a252de4b758fcb2abc6dd/src/PDE/Integrate/MultiMatTerms.cpp#L494)):*
> ```cpp
>     }
> 
>     std::vector< std::vector< tk::real > > AA_T(4, std::vector<tk::real>(4, 0.0));
> ```

This was a bug since previously I initialize AA_T with 1.
It should be 0 since we compute the elements of this matrix with operator `+=`


<!-- Sent from Reviewable.io -->

2020-12-21 23:07 UTC, adityakpandare requested changes
> Reviewed 1 of 9 files at r4, 28 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 9 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MP6RIqZ8-aJ2gTWPYlW:bhbiphe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

You are right. The limiter should produce the same results no matter the node-ordering. But I haven't figured it out why the water-air shocktube has a diff binary for that.
Also, the previous bound preserving limiter only limits the volume fraction between \eps and 1. So I just change the bound to [\eps, 1-\eps]. You can check the changes below. During the simulation of water-air shocktube testcase, I check the bound of volume fraction after limiting. It is in the range of [\eps, 1-\eps].
</blockquote></details>

Very strange. Let's make a note of this for now and move on.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 197 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MM1SfiW00JIO5wXoXSH:-MP6Skfv2jyc9Tju-OqJ:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L197)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done. Thank you!
</blockquote></details>

Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 256 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKuu1bm8G5XjYCBvevh:-MP6T3emCLNK8uJg71zs:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L256)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done.
Thank you!
</blockquote></details>

Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MP6T6Il4CtLhH8Ia4Ej:b-kw5j1h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done. Thanks!
</blockquote></details>

This still does not use the `energyIdx()` function in the loop extents (it's in there but commented out). Could you correct this?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 494 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MP6Q4vv1u_tQ9cwuVh1:-MP6TQKM26N8LMGP8aeN:bw9e7i3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74e5842da5ae1c41a11a252de4b758fcb2abc6dd/src/PDE/Integrate/MultiMatTerms.cpp#L494)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

This was a bug since previously I initialize AA_T with 1.
It should be 0 since we compute the elements of this matrix with operator `+=`
</blockquote></details>

Good catch. Why did the DGP1 test problems work before this bug was fixed?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 521 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MP6Tc_mAl0cwK52Kru1:-MP6Tc_mAl0cwK52Kru2:bi5et17) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74e5842da5ae1c41a11a252de4b758fcb2abc6dd/src/PDE/Integrate/MultiMatTerms.cpp#L521)):*
> ```cpp
>       //tk::real IPIV[4];
>       //tk::real Work[4];
>       //LAPACKE_dsysv( LAPACK_ROW_MAJOR, 'U', 4, 4, AA_T, 4, IPIV, u, 4, Work, 4, info);
> ```

I'm also taking a look at why this is not compiling.


<!-- Sent from Reviewable.io -->

2020-12-21 23:19 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 9 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 894 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc4Ntj3b0yxH7PlV8H:-MP6aIzR0gJGLX7RnNk6:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/PDE/Limiter.cpp#L894)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Very strange. Let's make a note of this for now and move on.
</blockquote></details>

Okay.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MP6_GX_14bc8vlytScp:b-maecn2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This still does not use the `energyIdx()` function in the loop extents (it's in there but commented out). Could you correct this?
</blockquote></details>

Sorry, I comment the code for debug of the regression testcase forgot to bring it back.
I will correct this. The code I should use is just in the comment.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 494 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MP6Q4vv1u_tQ9cwuVh1:-MP6_dt51eI5yx_1yZiM:b-fyht5s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74e5842da5ae1c41a11a252de4b758fcb2abc6dd/src/PDE/Integrate/MultiMatTerms.cpp#L494)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Good catch. Why did the DGP1 test problems work before this bug was fixed?
</blockquote></details>

I have no idea. But both results before and after this fix are really similar. The effects on the bug should be determined on the magnitude of the matrix. Maybe the magnitude is large for the testcase we have and plus one only add slight perturbations for the solution.


<!-- Sent from Reviewable.io -->

2020-12-22 18:12 UTC, WeizhaoLi2018 reviewed
Hi @jbakosi, it fix the problem. Thanks for the help. I will test the solver function to make sure it's implemented properly.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPAdVS21Odx3-cevlT9:bdgifii)* status: 31 of 33 files reviewed, 9 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-22 18:27 UTC, adityakpandare approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPAh86eD7UxUAxP39Qc:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 259 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MKutZqJ6Sj8nCxGa97I:-MP7FJpi5cw2JM5VAlPD:b-whxd16) ([raw file](https://github.com/quinoacomputing/quinoa/blob/25c34c75841ecea7c3c65a3ecb605e50519735f1/src/PDE/Integrate/MultiMatTerms.cpp#L259)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Sorry, I comment the code for debug of the regression testcase forgot to bring it back.
I will correct this. The code I should use is just in the comment.
</blockquote></details>

Thanks for fixing this.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 494 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MP6Q4vv1u_tQ9cwuVh1:-MP7FSN_6xMWpiHBCQ5-:bdbp02d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74e5842da5ae1c41a11a252de4b758fcb2abc6dd/src/PDE/Integrate/MultiMatTerms.cpp#L494)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I have no idea. But both results before and after this fix are really similar. The effects on the bug should be determined on the magnitude of the matrix. Maybe the magnitude is large for the testcase we have and plus one only add slight perturbations for the solution.
</blockquote></details>

Yeah, that's probably what's going on.


<!-- Sent from Reviewable.io -->

2020-12-22 18:29 UTC, jbakosi requested changes
> Reviewed 26 of 28 files at r5, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 4 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MPAgXCI3aTe2ymcgkr2:b-gl2ld1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

http://www.netlib.org/lapack/explore-html/d1/d7a/group__double_p_ocomputational_ga2f55f604a6003d03b5cd4a0adcfb74d6.html
</blockquote></details>

So can this go away now? Are you using lapack instead not calling this?
___
*[src/Inciter/DG.cpp, line 1777 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc1wsaCTKbEWE0Au3G:-MPAf_FjBIFjFGZdtv_A:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Inciter/DG.cpp#L1777)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I don't think we should tell the compiler to ignore the underflow here.
The reason is that the simulation will encounter this underflow issue when we called the `eval_state` function without the hard limiter. If we let that function ignore the underflow issue, I think it is not good for us to debug the code for the future development. So I add the hard limiter (the `if` statement in DG.cpp) in order to make sure we only ignore the underflow issue when some high order coefficients of the numerical solutions are close to zero.
</blockquote></details>

Okay.


<!-- Sent from Reviewable.io -->

2020-12-22 18:30 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 4 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MPAhrr_Dnnb0mkrg5Q2:b-tj6559) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

So can this go away now? Are you using lapack instead not calling this?
</blockquote></details>

Yes, I will push new commits to call the solver from lapack and remove this function.


<!-- Sent from Reviewable.io -->

2020-12-22 21:11 UTC, WeizhaoLi2018 reviewed
Hi guys, just pushed the commit to remove the LU function and call linear solvers from lapack.
The binary results for sod shocktube pass while the result for water-air shocktube fails the regression test. So I checked the final result for the water-air shocktube to make sure it's consistent with our previous results. And then update the regression test result for water-air shocktube test.
I think this branch is ready now. I will merge this into develop when it passes on Azure.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPBC_4cEKBkWtqT1iDP:b-r5n1fq)* status: 31 of 34 files reviewed, 4 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-22 23:37 UTC, adityakpandare approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPBo6xsAy2LI1UuWClg:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 14:34 UTC, jbakosi approved these changes
Looks good. Thanks, @weizhaoli2018 for the hard work on this.

> Reviewed 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPF0GeeBuWyffCTQGdD:b-u54hl3)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/Base/Vector.hpp, line 349 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MEc12rX2j4_IBPgdL59:-MPF-uylDbmaoFkFtqWf:bi3xsyd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e450fe43e81ccd87ffa5fa6a322791032623e116/src/Base/Vector.hpp#L349)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Yes, I will push new commits to call the solver from lapack and remove this function.
</blockquote></details>

Excellent! Thanks.


<!-- Sent from Reviewable.io -->

2020-12-23 15:18 UTC, jbakosi reviewed
Hey @weizhaoli2018 : d939d77 above makes the lapack call work with MKL's lapack, but inciter:multimat_waterair_shocktube_dgp1_pe1 fails the field-output diff (the diag passes).
```
329: Running text diff command: '/home/jbakosi/code/quinoa-tpl/install/clang-x86_64/bin/maddiff -b -t inciter:multimat_waterair_shocktube_dgp1_pe1 diag_dgp1.std diag waterair_shocktube_diag.ndiff.cfg'
329:
329: processing 'diag_dgp1.std'|'diag'
329: files 'diag_dgp1.std'|'diag' from test 'inciter:multimat_waterair_shocktube_dgp1_pe1' do not differ
329:     27 lines have been diffed
329:  + inciter:multimat_waterair_shocktube_dgp1_pe1       (0.00 s) -  1/ 1 : PASS
329: CMake Error at /home/jbakosi/code/quinoa/cmake/test_runner.cmake:375 (message):
329:   Binary diff command failed:
```
```
jbakosi@euler:~/code/quinoa/build/clang/tests/inciter/multimat/WaterAirShocktube/inciter:multimat_waterair_shocktube_dgp1_pe1:multimat_dgp1$ /home/jbakosi/code/quinoa-tpl/install/clang-x86_64/bin/exodiff -f exodiff_dg.cfg waterair_shocktube_dgp1.std.exo out.e-s.0.1.0

   *****************************************************************
              EXODIFF   (Version: 2.92) Modified: 2018-06-27
              Authors:  Richard Drake, rrdrake@sandia.gov
                        Greg Sjaardema, gdsjaar@sandia.gov
              Run on    2020/12/23   08:14:06 MST
   *****************************************************************

Reading first file ...
Reading second file ...
  FILE 1: /home/jbakosi/code/quinoa/tests/regression/inciter/multimat/WaterAirShocktube/waterair_shocktube_dgp1.std.exo
   Title: Written by Quinoa
          Dim = 3, Blocks = 2, Nodes = 491, Elements = 2312, Nodesets = 0, Sidesets = 6
          Vars: Global = 0, Nodal = 0, Element = 8, Nodeset = 0, Sideset = 0, Times = 2
  
  FILE 2: /home/jbakosi/code/quinoa/build/clang/tests/inciter/multimat/WaterAirShocktube/inciter:multimat_waterair_shocktube_dgp1_pe1/out.e-s.0.1.0
   Title: Written by Quinoa
          Dim = 3, Blocks = 2, Nodes = 491, Elements = 2312, Nodesets = 0, Sidesets = 6
          Vars: Global = 0, Nodal = 0, Element = 8, Nodeset = 0, Sideset = 0, Times = 2
  
  COMMAND FILE: /home/jbakosi/code/quinoa/tests/regression/inciter/multimat/WaterAirShocktube/exodiff_dg.cfg


Nodal coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
Time step values will be compared .. tol:    1e-08 (absolute), floor:        0
No Global variables on either file.
No Nodal variables on either file.
Element variables to be compared:
        volfrac1_numerical               tol:    1e-06 (absolute), floor:    1e-09
        volfrac2_numerical                       1e-06 (absolute),           1e-09
        density_numerical                        1e-06 (absolute),           1e-09
        x-velocity_numerical                     1e-06 (absolute),           1e-09
        y-velocity_numerical                     1e-06 (absolute),           1e-09
        z-velocity_numerical                     1e-06 (absolute),           1e-09
        pressure_numerical                       1e-06 (absolute),           1e-09
        total_energy_density_numerical           1e-06 (absolute),           1e-09
No Element Attribute variables on either file.
No Nodeset variables on either file.
No Sideset variables on either file.
Sideset Distribution Factors will be compared .. tol:    1e-06 (relative), floor:        0
  
  ==============================================================
  NOTE: All node and element ids are reported as global ids.

Sideset Distribution Factors:
  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, abs diff:  0.00000e+00 ---------
Element variables:
  --------- Time step 2, 2.5780002e-06 ~ 2.5780002e-06, abs diff:  4.23516e-22 ---------
Element variables:
   pressure_numerical              abs diff:  5.4256214e+08 ~  5.4256214e+08 = 2.86102e-06 (block 1, elmt 1445)

exodiff: Files are different
```

Can you please take a look at the field output in paraview and decide if you are okay with the diff above? If so, then loosen tolerances. Thanks.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPF9dImD0wseIb21bP2:b-wzrhqa)* status: 33 of 34 files reviewed, 3 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 15:20 UTC, jbakosi reviewed
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: 33 of 34 files reviewed, 3 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 16:47 UTC, WeizhaoLi2018 reviewed
Hi guys, my local results still show pass for water-air shocktube problem. Maybe because I don't have mkl on my machines. If you guys think the changes make sense, could you help me to update the regression test?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPFUIQ-1wPimKxutLAk:b-ge8ndn)* status: 33 of 34 files reviewed, 3 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 17:44 UTC, adityakpandare approved these changes
I think all that needs to be done is update tolerances, correct? The baselines are generated using a lapack build, and are fine as they are; right?

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPFgiQp9c9dhxyMswUQ:b-cytes9)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 17:47 UTC, jbakosi approved these changes
They are fine with lapack, but we need to loosen tolerances so the MKL build also passes. MKL is only tested at LANL using TC. @adityakpandare you manually trigger them via the dashboard.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPFhIu66qnEUCbXtBjF:b-uu0ydj)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 18:17 UTC, adityakpandare approved these changes
Okay. I'm doing that now.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPFoTXW-GgLTRbCijjH:b-aeryb8)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 20:12 UTC, adityakpandare approved these changes
@weizhaoli2018, please go ahead and merge this. The latest commits make sure that the MKL tests pass.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGDldP48X_koMDGLPL:bkkky3b)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 20:15 UTC, WeizhaoLi2018 reviewed
As soon as the branch pass on Azure, I will merge it into develop.
Thanks for the help!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGE84ZAzYDVRjE2ZT-:b-edy4nu)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 20:17 UTC, jbakosi approved these changes
Thanks a lot, guys! Please do not forget to sign the commit so our internal CI will not reject it. ;-)

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGEpwiCHkG8sgWG6sX:b6rgtxx)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 21:43 UTC, jbakosi requested changes
Hey guys! Hold on with this. I have the following tests failing with the intel compiler
```
The following tests FAILED:
        304 - inciter:compflow_euler_sodshocktube_p0p1_pe1 (Failed)
        306 - inciter:compflow_euler_sodshocktube_pdg_pe1 (Failed)
        308 - inciter:compflow_euler_sodshocktube_pdg_u0.8_pe4 (Failed)
        309 - inciter:compflow_euler_sodshocktube_pdg_u0.8_migr_pe4 (Failed)
        329 - inciter:multimat_waterair_shocktube_dgp1_pe1 (Failed)
```

There are no problems with current HEAD of develop, so it is this PR that introduces the failures. I'm building in RELEASE with the intel compiler and with MKL.

More details:
```
jbakosi@euler:~/code/quinoa/build/intel/tests/inciter/compflow/Euler/SodShocktube/inciter:compflow_euler_sodshocktube_p0p1_pe1$ /home/jbakosi/code/quinoa-tpl/install/clang-x86_64-smp/bin/exodiff -m -f exodiff_dg.cfg sod_shocktube_p0p1.std.exo out.e-s.0.1.0

   *****************************************************************
              EXODIFF   (Version: 2.92) Modified: 2018-06-27
              Authors:  Richard Drake, rrdrake@sandia.gov           
                        Greg Sjaardema, gdsjaar@sandia.gov          
              Run on    2020/12/23   14:38:34 MST
   *****************************************************************

Reading first file ... 
Reading second file ... 
  FILE 1: /home/jbakosi/code/quinoa/tests/regression/inciter/compflow/Euler/SodShocktube/sod_shocktube_p0p1.std.exo
   Title: Written by Quinoa
          Dim = 3, Blocks = 2, Nodes = 491, Elements = 2312, Nodesets = 0, Sidesets = 6
          Vars: Global = 0, Nodal = 0, Element = 6, Nodeset = 0, Sideset = 0, Times = 3

  FILE 2: /home/jbakosi/code/quinoa/build/intel/tests/inciter/compflow/Euler/SodShocktube/inciter:compflow_euler_sodshocktube_p0p1_pe1/out.e-s.0.1.0
   Title: Written by Quinoa
          Dim = 3, Blocks = 2, Nodes = 491, Elements = 2312, Nodesets = 0, Sidesets = 6
          Vars: Global = 0, Nodal = 0, Element = 6, Nodeset = 0, Sideset = 0, Times = 3

  COMMAND FILE: /home/jbakosi/code/quinoa/tests/regression/inciter/compflow/Euler/SodShocktube/exodiff_dg.cfg

exodiff: INFO .. Map option is not needed.

Nodal coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
Time step values will be compared .. tol:    1e-08 (absolute), floor:        0
No Global variables on either file.
No Nodal variables on either file.
Element variables to be compared:
        density_numerical                tol:    1e-07 (relative), floor:    1e-08
        x-velocity_numerical                     1e-07 (relative),           1e-08
        y-velocity_numerical                     1e-07 (relative),           1e-08
        z-velocity_numerical                     1e-07 (relative),           1e-08
        specific_total_energy_numerical          1e-07 (relative),           1e-08
        pressure_numerical                       1e-07 (relative),           1e-08
No Element Attribute variables on either file.
No Nodeset variables on either file.
No Sideset variables on either file.
Sideset Distribution Factors will be compared .. tol:    1e-06 (relative), floor:        0

  ==============================================================
  NOTE: All node and element ids are reported as global ids.

Sideset Distribution Factors:
  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, abs diff:  0.00000e+00 ---------
Element variables:
  --------- Time step 2, 1.0000000e-01 ~ 1.0000000e-01, abs diff:  0.00000e+00 ---------
Element variables:
  --------- Time step 3, 2.0000000e-01 ~ 2.0000000e-01, abs diff:  0.00000e+00 ---------
Element variables:
   x-velocity_numerical             rel diff:  1.2136375e-08 ~  1.2136373e-08 = 1.34767e-07 (block 1, elmt 536)

exodiff: Files are different
```

```
ctest -j32 -R inciter:compflow_euler_sodshocktube_pdg_pe1 -V
306:  -------------------------------------------------------------------------
306: Quinoa> Preparing workers ... done
306: Quinoa> Load balancing on (if enabled in Charm++)
306: Quinoa> Starting time stepping ...
306: Caught signal 8 (SIGFPE)
306: >>> Exception: Signal caught
306: >>>
306: >>> =========== CALL TRACE ===========
306: >>>
306: >>> /home/jbakosi/code/quinoa/build/intel/Base/libquinoa_base.so : tk::signalHandler(int)+0x12f
306: >>> /lib/x86_64-linux-gnu/libc.so.6 : ()+0x37840
306: >>> /home/jbakosi/code/quinoa-tpl/install/intel-x86_64/lib/libzoltan2.so.12 : __libm_log10_l9()+0x8b
306: >>> /home/jbakosi/code/quinoa-tpl/install/intel-x86_64/lib/libzoltan2.so.12 : ()+0x88c52
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : ()+0x367d98
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::eval_ndof(unsigned long, std::array<std::vector<double, std::allocator<double> >, 3ul> const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, inciter::FaceData const&, tk::Data<(unsigned char)0> const&, inciter::ctr::PrefIndicatorType, unsigned long, unsigned long, double, std::vector<unsigned long, std::allocator<unsigned long> >&)+0x346
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::DG::next()+0x8ea
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::DG::ResumeFromSync()+0x25f
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : CkMigratable::AtSync(int)+0x304
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::DG::evalLB(int)+0xef
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::DG::evalRestart()+0xe7
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::DG::step()+0x20e
306: >>> /home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so : inciter::CkIndex_DG::_call_step_void(void*, void*)+0xc
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : CkDeliverMessageFree()+0x37
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : CkLocRec::invokeEntry(CkMigratable*, void*, int, bool)+0x41
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : _processHandler(void*, CkCoreState*)+0x20b
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : CsdScheduleForever()+0x7d
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : CsdScheduler()+0x1e
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : ConverseInit()+0x605
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : charm_main()+0x27
306: >>> /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xeb
306: >>> /home/jbakosi/code/quinoa/build/intel/Main/inciter : _start()+0x2a
306: >>>
306: >>> ======= END OF CALL TRACE ========
306: >>>
306: >>>
306: >>> =========== STACK TRACE ==========
306: >>>
306: Stack trace (most recent call last):
306: #23   Object "/usr/lib/x86_64-linux-gnu/ld-2.28.so", at 0xffffffffffffffff, in 
306: #22   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x588429, in _start
306: #21   Source "../csu/libc-start.c", line 308, in __libc_start_main
306: #20   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x710926, in charm_main
306: #19   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x86a974, in ConverseInit
306: #18   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x86b98d, in CsdScheduler
306: #17   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x86ba0c, in CsdScheduleForever
306: #16   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x71e27a, in _processHandler(void*, CkCoreState*)
306: #15   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x742320, in CkLocRec::invokeEntry(CkMigratable*, void*, int, bool)
306: #14   Object "/home/jbakosi/code/quinoa/build/intel/Main/inciter", at 0x72cac6, in CkDeliverMessageFree
306: #13   Object "/home/jbakosi/code/quinoa/build/intel/Inciter/libquinoa_inciter.so", at 0x7ffff6ee2bfb, in inciter::CkIndex_DG::_call_step_void(void* [...]

2020-12-23 21:59 UTC, jbakosi commented
@adityakpandare : The TC intel builds can reproduce these failures.

2020-12-23 22:09 UTC, adityakpandare reviewed
Hmm.. Intel is also throwing an FPE from `spectral_decay()`. @weizhaoli2018, I see there's a division by U in this function. What happens when `U` is 0? Shouldn't there be a `U+\eps` so that division by zero is avoided? Also, has compflow changed at all in this set of commits?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGbyMz0axKexVegFT6:bb0o3zy)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 22:12 UTC, WeizhaoLi2018 reviewed
In theory, `U` won't be zero since in the evaluation of the error indicator `U` is the density of the fluid.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGdpaG7VI8Ka8zyjzS:b-5ebaw7)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 22:51 UTC, adityakpandare approved these changes
@weizhaoli2018: Okay. Could you try to figure out why an FPE is thrown then? Thanks.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGn2sKCsaibnFg8l4Y:b-ulcmir)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 22:54 UTC, adityakpandare reviewed
@weizhaoli2018: another potential problem is `dU` is zero, and `log10(0) = NaN`. This might be one thing you could look at.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGnfYyCurtB4hGV0NS:b-4s769c)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2020-12-23 23:07 UTC, WeizhaoLi2018 reviewed
I could upload a commit that remove the log calculation and see whether this will make the sod shocktube pass.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MPGoMGM1IxGx6EFHw5k:bo2u8qq)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-01-04 17:57 UTC, jbakosi approved these changes
> Reviewed 1 of 1 files at r11, 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 3 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/Inciter/PrefIndicator.cpp, line 107 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MQDXVmg7azivaa3gARj:-MQDXVmhE2vYXux19QBx:b-j3cfaj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/8ef55c650aec99dcafb9460fc55b428dc50979f0/src/Inciter/PrefIndicator.cpp#L107)):*
> ```cpp
>       }
> 
>       Ind[e] = dU / U;
> ```

I understand this fixes the floating point exception issue, but is this what we want for the p-ref algorithm?
___
*[src/Inciter/PrefIndicator.cpp, line 133 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MQDXfUy6ikUsBOXyayC:-MQDXfUy6ikUsBOXyayD:bylv4es) ([raw file](https://github.com/quinoacomputing/quinoa/blob/8ef55c650aec99dcafb9460fc55b428dc50979f0/src/Inciter/PrefIndicator.cpp#L133)):*
> ```cpp
> 
>   auto epsH = std::pow(10, -4 - tolref * 4.0);
>   auto epsL = std::pow(10, -6 - tolref * 8.0);
> ```

Same question here as above.


<!-- Sent from Reviewable.io -->

2021-01-04 18:16 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 3 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/PrefIndicator.cpp, line 107 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MQDXVmg7azivaa3gARj:-MQD_gx5DyhnFLi0IL9o:b-vbt0zz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/8ef55c650aec99dcafb9460fc55b428dc50979f0/src/Inciter/PrefIndicator.cpp#L107)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I understand this fixes the floating point exception issue, but is this what we want for the p-ref algorithm?
</blockquote></details>

This fix does not change anything in our p-ref algorithm. We only fix it by avoiding the log calculation applied directly on our indicator output and still the same thing as before when we tries to compare the indicator with the upper/lower threshold. I think it is a more rigorous way than our previous version.


<!-- Sent from Reviewable.io -->

2021-01-04 18:20 UTC, adityakpandare approved these changes
Thanks @weizhaoli2018 and @jbakosi! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MQDc9wL8eAJ0Cu-TcfK:batkm0c)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-01-04 18:23 UTC, adityakpandare approved these changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[tests/regression/inciter/compflow/Euler/SodShocktube/CMakeLists.txt, line 151 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MQDcnq0DqmL21H118VE:-MQDcnq0DqmL21H118VF:b-52dvoq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/8ef55c650aec99dcafb9460fc55b428dc50979f0/tests/regression/inciter/compflow/Euler/SodShocktube/CMakeLists.txt#L151)):*
> ```CMake
> else()
>   set(compflow_euler_sodshocktube_p0p1_BIN_DIFF_PROG_CONF exodiff_dg.cfg)
> endif()
> ```

Nice! I'll remember this. Thanks!


<!-- Sent from Reviewable.io -->

2021-01-04 18:25 UTC, jbakosi reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[tests/regression/inciter/compflow/Euler/SodShocktube/CMakeLists.txt, line 151 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-MQDcnq0DqmL21H118VE:-MQDdGtX7QQxcpHmn2_O:baczzva) ([raw file](https://github.com/quinoacomputing/quinoa/blob/8ef55c650aec99dcafb9460fc55b428dc50979f0/tests/regression/inciter/compflow/Euler/SodShocktube/CMakeLists.txt#L151)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice! I'll remember this. Thanks!
</blockquote></details>

Yet another dimension on which we can make this code more complicated. ;-)


<!-- Sent from Reviewable.io -->

2021-01-04 20:15 UTC, jbakosi reviewed
This is now ready to merge. It seems to be passing azure as well as TC. <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/439#-:-MQE1LlVCKly0scfMV17:b-b7trhy)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-01-05 08:57 UTC, merged