Kuzmin p2
quinoacomputing/quinoa pull request #496
Opened 2021-06-23 17:38 UTC by WeizhaoLi2018

This branch adds the vertex-based P2 limiter for Compflow

2021-06-23 17:53 UTC, WeizhaoLi2018 reviewed
Hi guys, before we merge this branch, I still have one last issue about the parallel consistency.
For example, when I run the Gaussian advection testcase for DGP2 with vertex-based limiter for 1000 iteration, the error returned for serial is 6.842884e-04 while for 8-core parallel result shows 6.914861e-04.

I think you guys could take a look at the code and maybe we can discuss about it. Thank you!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-MctzV-v-nSfwtThd9ZU:bmkjpbr)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @adityakpandare and @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-23 17:56 UTC, adityakpandare reviewed
@weizhaoli2018, is this difference observed in the multimat or the compflow Gaussian advection problem?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mcu-l3y7GO6YouvY7ND:br941yf)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-23 18:03 UTC, WeizhaoLi2018 reviewed
The difference is observed for compflow Gaussian advection problem.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mcu1JXI-rsTkScd3K4U:bubbayc)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @adityakpandare and @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-23 18:07 UTC, adityakpandare reviewed
Does the difference vanish if you do not use the limiter with DGP2 for the same problem?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mcu2J701dU8kC4ZMSem:b-gqciqm)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-23 18:39 UTC, WeizhaoLi2018 reviewed
Without limiter, there is no such issue. And for P1 with vertex-based limiter, there is no such issue either. So I think it should be something within the part of P2 limiter.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mcu9aSECh3TJiwW9Wc-:b-775dfj)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-24 15:18 UTC, adityakpandare reviewed
Agreed. I'll take a look at it. However, I see that a lot of other tests are failing for this branch too. Could you fix that first? If other tests are failing, there is no easily apparent place to start debugging.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-McyaEt31kt56-j_5y3X:bflajds)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-06-25 18:28 UTC, WeizhaoLi2018 reviewed
I am working on that and will push new commits to fix the online testing failure ASAP.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Md3QUrB83LO39uCnROn:b-yd34ln)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-07-07 14:50 UTC, adityakpandare reviewed
Looks like the parallel-serial inconsistency is fixed? That's great @weizhaoli2018! Now that we know what was causing the issue, can you reinstate the `std::max`'s in `DGCompFlow`, `DGMultiMat` and `DGTransport`?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Me0Qyb0E7Ba4uFMAs75:b-655ia5)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-07-07 16:40 UTC, WeizhaoLi2018 reviewed
@adityakpandare Yes, the parallel issue is fixed and I just pushed new commits to bring back the max function. Thanks for the remind!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Me0peWkCQM4hEVVk4Xv:b19l30w)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @jbakosi)



<!-- Sent from Reviewable.io -->

2021-07-08 17:03 UTC, jbakosi requested changes
I have a few, mostly `software-engineering-style` comments.

> Reviewed 7 of 13 files at r1, 3 of 6 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Me63hoa0KHP_fA5f-Q3:bc4ofre)* status: all files reviewed, 27 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1954 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5lqjb2ByvPlIxY2Dr:-Me5lqjc9WWM6A4qefx1:b9t7bo6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1954)):*
> ```cpp
>   for (const auto& [c,n] : Disc()->NodeCommMap())
>   {
>     auto large = std::numeric_limits< tk::real >::max();
> ```

There is no reason to put `large` inside the loop.
___
*[src/Inciter/DG.cpp, line 1965 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5mnG2EyfmZ_NmdRPh:-Me5mnG2EyfmZ_NmdRPi:b1uowb2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1965)):*
> ```cpp
>       {
>         for(std::size_t k = 0; k < ncomp; k++)
>           u[k*m_ndof_NodalExtrm+idof] = -large;
> ```

What is the reason to access the array with large strides? I.e.,
```
      for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
        for(std::size_t k = 0; k < ncomp; k++)
          u[k*m_ndof_NodalExtrm+idof] = ...
```
will jump `m_ndof_NodalExtrm` entries for every `idof` access instead of accessing it continuously. I would flip the loops as
```
      for(std::size_t k = 0; k < ncomp; k++)
        for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
          u[k*m_ndof_NodalExtrm+idof] = ...
```
or the data access
```
      for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
        for(std::size_t k = 0; k < ncomp; k++)
          u[idof*ncomp+k] = ...
```
Though this should be measured, I believe the latter two will have more favorable cache access as they are more contiguous, than the first one.
___
*[src/Inciter/DG.cpp, line 2377 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5pS1YEiO019yQjupZ:-Me5pS1ZCFXr6yylp6mD:bwh29ix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L2377)):*
> ```cpp
>   m_volfracExtr.resize( nelem );
>   //m_uNodalExtrm.resize( d->Bid().size() );
>   //m_pNodalExtrm.resize( d->Bid().size() );
> ```

Do we need the commented code?
___
*[src/Inciter/PrefIndicator.cpp, line 296 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5q7im-42qZ3yfhM-0:-Me5q7im-42qZ3yfhM-1:b-nnzj3n) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L296)):*
> ```cpp
>                          ncomp_t ncomp,
>                          const std::size_t ndof,
>                          const std::vector< std::size_t >& ndofel,
> ```

If the function only accesses `ndofel[e]`, let's only pass that instead of the whole vector.
___
*[src/Inciter/PrefIndicator.cpp, line 303 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5pvaZ9o1Xkb6tTekZ:-Me5pva_C6kA18pM2ENz:b970nk9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L303)):*
> ```cpp
> //! \param[in] ncomp Number of scalar components in this PDE system
> //! \param[in] ndof Number of degrees of freedom in the solution
> //! \param[in] ndofel Vector of local number of degrees of freedome
> ```

"freedom"
___
*[src/PDE/Limiter.cpp, line 76 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63cz_2n-qSSpVNlt9:-Me63cz_2n-qSSpVNltA:b-uaoojh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L76)):*
> ```cpp
>                  tk::Fields& U,
>                  tk::Fields& P,
>                  std::size_t nmat )
> ```

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
___
*[src/PDE/Limiter.cpp, line 201 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63ZI1BQS75BgrDqaq:-Me63ZI1BQS75BgrDqar:b-uaoojh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L201)):*
> ```cpp
> 
> void
> SuperbeeMultiMat_P1(
> ```

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
___
*[src/PDE/Limiter.cpp, line 302 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63V7R0OP1R7JNRhXF:-Me63V7R0OP1R7JNRhXG:b-ik4cj7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L302)):*
> ```cpp
> 
> void
> VertexBasedTransport_P1(
> ```

Based on the function name, this should probably be in `dg::Transport`. Will this be called (i.e., should this be accessible) from anywhere else?
___
*[src/PDE/Limiter.cpp, line 394 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63TFEDgJgVohxdBSf:-Me63TFEDgJgVohxdBSg:bt3qwjd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L394)):*
> ```cpp
> 
> void
> VertexBasedCompflow_P1(
> ```

Based on the function name, this should probably be in `dg::CompFlow`. Will this be called (i.e., should this be accessible) from anywhere else?
___
*[src/PDE/Limiter.cpp, line 468 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6-RDY9oF7le0xt4OA:-Me6-RDZ54Gg1E9plg_F:bt3qwjd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L468)):*
> ```cpp
> 
> void
> VertexBasedCompflow_P2(
> ```

Based on the function name, this should probably be in `dg::CompFlow`. Will this be called (i.e., should this be accessible) from anywhere else?
___
*[src/PDE/Limiter.cpp, line 506 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me604pr4_tqR_G7wJpv:-Me604pr4_tqR_G7wJpw:b-ukcxsa) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L506)):*
> ```cpp
> 
>   // Copy field data U to U_lim. U_lim will store the limited solution
>   // temperally to avoid the limited solution will be used when finding
> ```

"temporally"
___
*[src/PDE/Limiter.cpp, line 538 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me60n7kCLBT51AAEXT5:-Me60n7kCLBT51AAEXT6:bgk5mhk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L538)):*
> ```cpp
>       // The vector used to store the numerical solution with Taylor basis
>       std::vector< std::vector< tk::real > > unk;
>       unk.resize(ncomp, std::vector< tk::real >(dof_el, 0.0));
> ```

Or, shorter
```
      std::vector< std::vector< tk::real > > unk( ncomp, std::vector< tk::real >(dof_el, 0.0) );
```
___
*[src/PDE/Limiter.cpp, line 556 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me61CVO6-eCg9mnanaK:-Me61CVO6-eCg9mnanaL:bwfm035) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L556)):*
> ```cpp
> 
>       // limit conserved quantities
>       phic_p1 = VertexBasedFunction(unk, U, esup, inpoel, coord, geoElem, e,
> ```

So if `VertexBasedFunction`'s job is to limit, can we pick a name that expresses that fact better? (So the code becomes self-documenting.)
___
*[src/PDE/Limiter.cpp, line 613 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63Nk3EtNNp7e-_6W-:-Me63Nk3EtNNp7e-_6W0:b-uaoojh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L613)):*
> ```cpp
> 
> void
> VertexBasedMultiMat_P1(
> ```

Based on th [...]

2021-07-08 17:10 UTC, jbakosi requested changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: all files reviewed, 27 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/PDE/Integrate/Basis.cpp, line 565 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5voXd-rELJ_m0YMFe:-Me6526fEz3M1LiJhoRk:b54txre) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Integrate/Basis.cpp#L565)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Seems like a matrix vector product. If so, why don't we write (vectorizable) free functions in `Base/Vector.[ch]pp` using `std::array`s and just use those so the reader has a fighting chance at understanding the code.
</blockquote></details>

Actually, working with `std::array` and attempting to make those free functions vectorizable might _not_ both work at the same time. Nevertheless, I would use `std::array`s first and abstract this away if I can. _Then_ think about how it could be vecrtorized.


<!-- Sent from Reviewable.io -->

2021-07-13 19:19 UTC, adityakpandare requested changes
I have a few comments below. Thanks!

> Reviewed 6 of 13 files at r1, 3 of 6 files at r2, 4 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-MeWIq304JA0vDn0is-B:bsb11dq)* status: all files reviewed, 41 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 343 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6022P1mrS9_VPad5U:-Me6022P1mrS9_VPad5V:b-nb1urw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.hpp#L343)):*
> ```cpp
>     tk::Fields m_rhs;
>     //! Vector of nodal extrema for conservative variables
>     std::vector< std::vector<tk::real> > m_uNodalExtrm;
> ```

Why is the `tk::Fields` type not okay for these?
___
*[src/Inciter/DG.cpp, line 143 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6LSsm3zB-hSAW6Xcr:-Me6LSsm3zB-hSAW6Xcs:b-7bjs3o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L143)):*
> ```cpp
>   auto rdof = g_inputdeck.get< tag::discr, tag::rdof >();
>   if(rdof > 4)
>     m_ndof_NodalExtrm = 4;
> ```

Let's either move this line next to the if-test like:
```
  if (rdof > 4) m_ndof_NodalExtrm = 4;
```
or add parenthesis like:
```
  if (rdof > 4) {
    m_ndof_NodalExtrm = 4;
  }
```
The way it is now gets me confused about the lines following this: are they in the if-test or not. I know they are not, but the code is confusing to read this way.
___
*[src/Inciter/DG.cpp, line 1843 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6USjb9XX0s3Dh9Xp0:-Me6USjb9XX0s3Dh9Xp1:b-a5cq8w) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1843)):*
> ```cpp
>         auto min_mark = max_mark + ncomp * m_ndof_NodalExtrm;
>         m_uNodalExtrm[i][max_mark] = -large;
>         m_uNodalExtrm[i][min_mark] =  large;
> ```

Since the min and max values are always accessed one-after-the-other (and they are accessed **several** times), they should be stored near each other for cache friendliness, rather than far apart. In other words, the min-value of a dof should be stored right after the max-value of that dof. The index/access would be:
```
max_mark = 2*m_ndof_NodalExtrm*c + 2*idof;
min_mark = 2*m_ndof_NodalExtrm*c + 2*idof + 1;
```
And the loop would be the same. Also, I recommend that these index "marks" are coded specifically in the way shown above, everywhere they are needed, so that it is easier for the reader to understand how the vector is indexed into.
___
*[src/Inciter/DG.cpp, line 1862 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6NHkkDZsSvYbP9OGp:-Me6NHkkDZsSvYbP9OGq:bg2xbr1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1862)):*
> ```cpp
>     for (const auto& eq : g_dgpde)
>       eq.evalNodalExtrm(ncomp, nprim, m_ndof_NodalExtrm, d->bndel(), m_inpoel,
>         m_coord, gid, bid, m_u, m_p, m_uNodalExtrm, m_pNodalExtrm);
> ```

Like @jbakosi suggested, this function should not reside in `DGPDE`, but right here in `DG.cpp`, basically because it has no physics associated with it.
___
*[src/Inciter/DG.cpp, line 1965 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5mnG2EyfmZ_NmdRPh:-Me6laDQ0zkJ_kb3DaBf:b-vzqvqh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1965)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

What is the reason to access the array with large strides? I.e.,
```
      for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
        for(std::size_t k = 0; k < ncomp; k++)
          u[k*m_ndof_NodalExtrm+idof] = ...
```
will jump `m_ndof_NodalExtrm` entries for every `idof` access instead of accessing it continuously. I would flip the loops as
```
      for(std::size_t k = 0; k < ncomp; k++)
        for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
          u[k*m_ndof_NodalExtrm+idof] = ...
```
or the data access
```
      for(std::size_t idof=0; idof<m_ndof_NodalExtrm; idof++)
        for(std::size_t k = 0; k < ncomp; k++)
          u[idof*ncomp+k] = ...
```
Though this should be measured, I believe the latter two will have more favorable cache access as they are more contiguous, than the first one.
</blockquote></details>

This is similar to my suggestion before. I strongly suggest re-arranging the storage pattern, so that it is more cache-friendly.
___
*[src/Inciter/PrefIndicator.cpp, line 293 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6Ko3B0SoLL4lKuL3_:-Me6Ko3B0SoLL4lKuL3a:b-l558aq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L293)):*
> ```cpp
> }
> 
> tk::real eval_indicator( std::size_t e,
> ```

lets call this something more indicative of it's function. Does this indicate shocks or gradients? If yes, let's call this `evalGradientIndicator()` or `evalDiscontinuityIndicator()`, or something similar.
___
*[src/Inciter/PrefIndicator.cpp, line 296 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5q7im-42qZ3yfhM-0:-Me6DRLX1VbhIw5xhXBi:b-pbdqz3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L296)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If the function only accesses `ndofel[e]`, let's only pass that instead of the whole vector.
</blockquote></details>

Agreed.
___
*[src/PDE/Limiter.cpp, line 76 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63cz_2n-qSSpVNlt9:-Me6Dmse9P3hpyGxfMbp:b-a5alaz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L76)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

@jbakosi, this function is going away once I merge https://github.com/quinoacomputing/quinoa/pull/500
___
*[src/PDE/Limiter.cpp, line 201 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63ZI1BQS75BgrDqaq:-Me6E0FYEmrHp5vYjveN:b-jj8z0x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L201)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

We have put all the limiters in Limiters.cpp, regardless of whether they are for Transport, Compflow or Multimat. They are not called elsewhere. I do not mind having them in `DG::MultiMat` if you think that's more appropriate, but let's do that in another pull request.
___
*[src/PDE/Limiter.cpp, line 506 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me604pr4_tqR_G7wJpv:-Me6F8KQ-cUeAHT1rYG-:b-ppk93v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L506)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

"temporally"
</blockquote></details>

@weizhaoli2018, I think you mean "temporarily". Also, because of incorrect grammar, I will be difficult for the reader to understand what you're trying to convey here. Please correct the grammar as: "... store the limited solution temporarily, so that the limited solution is NOT used to find the min/max bounds...". Capitalize the "NOT" so that it is emphasized.
___
*[src/PDE/Limiter.cpp, line 584 at r3] [...]

2021-07-13 21:18 UTC, jbakosi requested changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: all files reviewed, 40 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 76 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63cz_2n-qSSpVNlt9:-MeWgDb5-i_lduPZwYee:brxp9sq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L76)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

@jbakosi, this function is going away once I merge https://github.com/quinoacomputing/quinoa/pull/500
</blockquote></details>

Sounds good.
___
*[src/PDE/Limiter.cpp, line 201 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63ZI1BQS75BgrDqaq:-MeWgJW59Gq0TPBG6pbO:bhbzp52) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L201)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We have put all the limiters in Limiters.cpp, regardless of whether they are for Transport, Compflow or Multimat. They are not called elsewhere. I do not mind having them in `DG::MultiMat` if you think that's more appropriate, but let's do that in another pull request.
</blockquote></details>

Okay. Does it make sense to use a particular limiter for multiple (types of) equations? If not, I vote for moving them, but I also understand the reason behind grouping all limiters into their own file.
___
*[src/PDE/Limiter.cpp, line 506 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me604pr4_tqR_G7wJpv:-MeWghoh8ViYFUEmW1Jc:b-42ce9f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L506)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

@weizhaoli2018, I think you mean "temporarily". Also, because of incorrect grammar, I will be difficult for the reader to understand what you're trying to convey here. Please correct the grammar as: "... store the limited solution temporarily, so that the limited solution is NOT used to find the min/max bounds...". Capitalize the "NOT" so that it is emphasized.
</blockquote></details>

Oh, okay. Thanks for explanation, @adityakpandare.
___
*[src/PDE/Limiter.cpp, line 731 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63FUz6jzTCFtWJkkE:-MeWgz-xBmh9MgJnLR0q:b-8ack9x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L731)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

What I meant when I named these as "WENOFunctions" is that these implement the limiter-function kernels. I did not mean "function" in the C++/programming sense of the term.
</blockquote></details>

Yeah, but still, the other meaning remains as _function_. Does it help in understanding/readability? (I can be convinced that it does.) Maybe call them _kernel_?
___
*[src/PDE/Limiter.cpp, line 1441 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me62MyR5BpADQRuMzwu:-MeWhzuPA895iyxs4Khg:bdzkvve) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L1441)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Not every limiter preserves specified bounds. e.g. if we use WENO or Vertex-based or some other such limiter on a scalar field that is supposed to be bounded between 0 to 1 for a high-order scheme, most likely those bounds will be violated (first in very small magnitudes that eventually grow). This bound-preserving limiter is specifically meant to *enforce* such bounds, but it does not suppress oscillations, like the other limiters would. So a combination of oscillation-suppressing and bound-preserving limiters is used to obtain a non-oscillatory *and* bounded solution.
</blockquote></details>

Oh, cool. Thanks for the explanation. Should we also include this explanation in the code as comments somewhere? Maybe here as `\details`?


<!-- Sent from Reviewable.io -->

2021-07-14 14:18 UTC, adityakpandare reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: all files reviewed, 40 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 201 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63ZI1BQS75BgrDqaq:-Me_CbOw7TBvH3mVXr7q:b8jnwvf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L201)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Okay. Does it make sense to use a particular limiter for multiple (types of) equations? If not, I vote for moving them, but I also understand the reason behind grouping all limiters into their own file.
</blockquote></details>

Nope, it doesn't. You're right. I have created an issue (https://github.com/quinoacomputing/quinoa/issues/503), and I'll clean this up soon. Thanks for pointing it out.
___
*[src/PDE/Limiter.cpp, line 731 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63FUz6jzTCFtWJkkE:-Me_IMNpCtOR9Fat93QD:b-tpnktq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L731)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, but still, the other meaning remains as _function_. Does it help in understanding/readability? (I can be convinced that it does.) Maybe call them _kernel_?
</blockquote></details>

Yeah, I'm also on the fence about this. `WENOkernel()` seems too generic. Other options: `WENO()`, `getWENO()`. Thoughts about these?
___
*[src/PDE/Limiter.cpp, line 1441 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me62MyR5BpADQRuMzwu:-Me_LQjU5b1yKLF3enqh:b-g009yv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L1441)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Oh, cool. Thanks for the explanation. Should we also include this explanation in the code as comments somewhere? Maybe here as `\details`?
</blockquote></details>

Good idea. @weizhaoli2018, could you add the explanation: "This bound-preserving limiter is specifically meant to enforce bounds [0,1], but it does not suppress oscillations like the other 'TVD' limiters. TVD limiters on the other hand, do not preserve such bounds. A combination of oscillation-suppressing and bound-preserving limiters can obtain a non-oscillatory and bounded solution." in \details?


<!-- Sent from Reviewable.io -->

2021-07-14 17:19 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 10 of 47 files reviewed, 40 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 343 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6022P1mrS9_VPad5U:-MeWNsPvBI9GYemMvywf:b8bb0m9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.hpp#L343)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why is the `tk::Fields` type not okay for these?
</blockquote></details>

Both are okay here. But I think a two-dimensional vector could do the job well. Because in my opinion, `Fields` are more like a 3d vector.
___
*[src/Inciter/DG.cpp, line 143 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6LSsm3zB-hSAW6Xcr:-MeWOQhv3rVK_irwPy1O:b1uo7ql) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L143)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's either move this line next to the if-test like:
```
  if (rdof > 4) m_ndof_NodalExtrm = 4;
```
or add parenthesis like:
```
  if (rdof > 4) {
    m_ndof_NodalExtrm = 4;
  }
```
The way it is now gets me confused about the lines following this: are they in the if-test or not. I know they are not, but the code is confusing to read this way.
</blockquote></details>

Thanks for pointing out this! Just fixed!
___
*[src/Inciter/DG.cpp, line 1843 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6USjb9XX0s3Dh9Xp0:-Me_zUdB7jRrFpB9YhZd:bm4tbsc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1843)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Since the min and max values are always accessed one-after-the-other (and they are accessed **several** times), they should be stored near each other for cache friendliness, rather than far apart. In other words, the min-value of a dof should be stored right after the max-value of that dof. The index/access would be:
```
max_mark = 2*m_ndof_NodalExtrm*c + 2*idof;
min_mark = 2*m_ndof_NodalExtrm*c + 2*idof + 1;
```
And the loop would be the same. Also, I recommend that these index "marks" are coded specifically in the way shown above, everywhere they are needed, so that it is easier for the reader to understand how the vector is indexed into.
</blockquote></details>

Just changed the data structure of `NodalExtrm`.
___
*[src/Inciter/DG.cpp, line 1862 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6NHkkDZsSvYbP9OGp:-MeWRp_QANmWy_QYUBad:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1862)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Like @jbakosi suggested, this function should not reside in `DGPDE`, but right here in `DG.cpp`, basically because it has no physics associated with it.
</blockquote></details>

Done! Thanks!
___
*[src/Inciter/DG.cpp, line 1954 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5lqjb2ByvPlIxY2Dr:-MeR4f9x0TlCuAnLqgqS:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1954)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

There is no reason to put `large` inside the loop.
</blockquote></details>

Done! Thanks!
___
*[src/Inciter/DG.cpp, line 1965 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5mnG2EyfmZ_NmdRPh:-Me_zcTh9KJi-2FtkQL5:b-s72nn9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L1965)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is similar to my suggestion before. I strongly suggest re-arranging the storage pattern, so that it is more cache-friendly.
</blockquote></details>

Just changed the data structure of `NodalExtrm` so that the access is continuous
___
*[src/Inciter/DG.cpp, line 2377 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5pS1YEiO019yQjupZ:-MeR5gQq-0QySQn38w6L:b7sk4i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.cpp#L2377)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Do we need the commented code?
</blockquote></details>

Sorry about that. I forgot to remove the useless code. Just done!
___
*[src/Inciter/PrefIndicator.cpp, line 293 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6Ko3B0SoLL4lKuL3_:-MeWTvTZC5CTboPd7Ljd:b-896fja) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L293)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

lets call this something more indicative of it's function. Does this indicate shocks or gradients? If yes, let's call this `evalGradientIndicator()` or `evalDiscontinuityIndicator()`, or something similar.
</blockquote></details>

Done!
___
*[src/Inciter/PrefIndicator.cpp, line 296 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5q7im-42qZ3yfhM-0:-MeR6An21e_r-Kn2qEXO:b-896fja) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L296)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If the function only accesses `ndofel[e]`, let's only pass that instead of the whole vector.
</blockquote></details>

Done!
___
*[src/Inciter/PrefIndicator.cpp, line 303 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5pvaZ9o1Xkb6tTekZ:-MeR6BcA5Xr0sMkrKv4G:b-xrd0w5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L303)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

"freedom"
</blockquote></details>

Thanks for finding this typo!
___
*[src/PDE/Limiter.cpp, line 506 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me604pr4_tqR_G7wJpv:-MeR7Xj98sPEvOWGb_Qp:bd69rys) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L506)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

@weizhaoli2018, I think you mean "temporarily". Also, because of incorrect grammar, I will be difficult for the reader to understand what you're trying to convey here. Please correct the grammar as: "... store the limited solution temporarily, so that the limited solution is NOT used to find the min/max bounds...". Capitalize the "NOT" so that it is emphasized.
</blockquote></details>

Just add it to comments. Thanks!
___
*[src/PDE/Limiter.cpp, line 538 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me60n7kCLBT51AAEXT5:-MeR7hXm-0svyDQTc6nA:b-ppvcdy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L538)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Or, shorter
```
      std::vector< std::vector< tk::real > > unk( ncomp, std::vector< tk::real >(dof_el, 0.0) );
```
</blockquote></details>

Put this in function `TransformDubinerToTaylor`.
___
*[src/PDE/Limiter.cpp, line 556 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me61CVO6-eCg9mnanaK:-MeRIUvi4yLSaoayzf_3:bjjjmy6) ([raw file](https://github.com/quinoacomputing/quinoa/blo [...]

2021-07-16 00:11 UTC, WeizhaoLi2018 reviewed
Hi guys, I just pushed all the commits to modify the codes according to your comments.
let me know if there is something I missed or some pieces of code require further modifications.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-MegcK3D5YfDwJJKVRbE:bwj2mfr)* status: 10 of 47 files reviewed, 40 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-07-16 15:59 UTC, adityakpandare requested changes
I have a couple more comments.

> Reviewed 7 of 37 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mek1q9S6ngqrZ2kseHt:bofqr9w)* status: 20 of 47 files reviewed, 28 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 343 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6022P1mrS9_VPad5U:-Mea356K-8qL3HpV2w8j:b979vx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/DG.hpp#L343)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Both are okay here. But I think a two-dimensional vector could do the job well. Because in my opinion, `Fields` are more like a 3d vector.
</blockquote></details>

Okay. Thanks!
___
*[src/Inciter/DG.cpp, line 2120 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MejoMIY6HXbybU4ngfF:-MejoMIY6HXbybU4ngfG:b9bkkp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/Inciter/DG.cpp#L2120)):*
> ```cpp
>             }
>           }
>         }
> ```

Looks great!
___
*[src/Inciter/PrefIndicator.cpp, line 293 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6Ko3B0SoLL4lKuL3_:-Mea3n734Ayp7DwpkaV_:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/Inciter/PrefIndicator.cpp#L293)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Thanks!
___
*[src/PDE/Limiter.cpp, line 302 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63V7R0OP1R7JNRhXF:-Meju6Up9Pwfi1mrGti3:b-mjexwe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L302)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::Transport`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

Added an issue https://github.com/quinoacomputing/quinoa/issues/503.
___
*[src/PDE/Limiter.cpp, line 394 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63TFEDgJgVohxdBSf:-Meju9wTD7ZjNcL95LSC:b-mjexwe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L394)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::CompFlow`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

Added an issue https://github.com/quinoacomputing/quinoa/issues/503.
___
*[src/PDE/Limiter.cpp, line 468 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me6-RDY9oF7le0xt4OA:-MejuBqw6ryhcuVUTqkF:b-mjexwe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L468)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::CompFlow`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

Added an issue https://github.com/quinoacomputing/quinoa/issues/503.
___
*[src/PDE/Limiter.cpp, line 584 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeVQTEAEi45g-aMKuO_:-Mea4NqG7fKSG2xAwxcP:b-ouf9u3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L584)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Let me know whether the new function declaration is good enough or not.
</blockquote></details>

I'm not sure if it is a good idea to have `unk` as an input argument as well as the returned quantity. @jbakosi, what do you think?
___
*[src/PDE/Limiter.cpp, line 613 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63Nk3EtNNp7e-_6W-:-MejqVA-1sIuehUWlSYi:b-mjexwe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L613)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

Added an issue https://github.com/quinoacomputing/quinoa/issues/503.
___
*[src/PDE/Limiter.cpp, line 1119 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeVR8Yt2ct9x6njf-fB:-Mek1BwYECuWzotVgsVV:b-9exwcw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L1119)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I know our yesterday's discussion came to inclusion that we didn't need unk here. But later I just realized why I have written this part of code as if and else.
So here we tried to evaluate P1 solution at gauss points (which is `state`). When it comes to P2 solution we are actually evaluating `state = P0 + P1` (If you could check the for loop in evaluating `unk` shows `idof < 4`). And for different basis functions, say `P0 + P1_Taylor` are not equl to `P0+P1_Dubiner` for P2 solution and that's why we need `unk` here.
</blockquote></details>

"And for different basis functions, say `P0 + P1_Taylor` are not equal to `P0+P1_Dubiner` for P2 solution": this is what I expected, but was not sure of during our discussion. I understand now. Thanks!
___
*[src/PDE/Limiter.cpp, line 1338 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me62DSn4fe7csrF3xKl:-Meju3VT0iIeumRxBwSE:b-mjexwe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L1338)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Based on the function name, this should probably be in `dg::MultiMat`. Will this be called (i.e., should this be accessible) from anywhere else?
</blockquote></details>

Added an issue https://github.com/quinoacomputing/quinoa/issues/503.
___
*[src/PDE/Limiter.cpp, line 590 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Mea4aYX1bR3MSldftoj:-Mea4aYX1bR3MSldftok:b-l3nu7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/177a4783226ab4027739ea295497d04b91ccbf03/src/PDE/Limiter.cpp#L590)):*
> ```cpp
>         auto mark = c*rdof;
>         for(std::size_t idof = 0; idof < rdof; idof++)
>           U_lim(e, mark+idof, offset) = unk[c][idof];
> ```

It seems here that we are modifying the cell-avg too; which is left to the previous code to decide if they have modified it in `unk`. Instead, let's have the loop range as `for(std::size_t idof = 1; idof < rdof; idof++)`? That way it is absolutely clear that we do not modify the cell-avg.


<!-- Sent from Reviewable.io -->

2021-07-16 19:50 UTC, jbakosi requested changes
> Reviewed 34 of 37 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: all files reviewed, 12 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 556 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me61CVO6-eCg9mnanaK:-MekkQpJC4U5m65S5248:bwa3ykj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L556)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Do you mean something like `VertexBasedLimiting`?
</blockquote></details>

Sure. What do you think @adityakpandare ?
___
*[src/PDE/Limiter.cpp, line 584 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeVQTEAEi45g-aMKuO_:-MekkqKL-PBXpkOpHJb1:beltc2s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L584)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I'm not sure if it is a good idea to have `unk` as an input argument as well as the returned quantity. @jbakosi, what do you think?
</blockquote></details>

Yeah, I think having it both passed and returning is confusing to read. I think if it is created here from scratch, it should be returned, and if we only modify it, it should be passed as non-const ref, but not both.
___
*[src/PDE/Limiter.cpp, line 731 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63FUz6jzTCFtWJkkE:-Mekls2W2Y8MLIaevSPS:bw2onh7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L731)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yeah, I'm also on the fence about this. `WENOkernel()` seems too generic. Other options: `WENO()`, `getWENO()`. Thoughts about these?
</blockquote></details>

I vote for the shortest. ;-)
___
*[src/PDE/Integrate/Basis.hpp, line 79 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknIsG97Ht1mfXM-fv:-MeknIsG97Ht1mfXM-fw:b-hf2v44) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.hpp#L79)):*
> ```cpp
> //! Transform the solution with Dubiner basis to the solution with Taylor basis
> std::vector< std::vector< tk::real > >
> TransformDubinerToTaylor(
> ```

Does it need the prefix `Transform`? Isn't it obvious based on the function name `DubinerToTaylor` that it is a transformation?
___
*[src/PDE/Integrate/Basis.hpp, line 90 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknZKZDjKtKEGbDDIH:-MeknZKZDjKtKEGbDDII:b5rkt7i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.hpp#L90)):*
> ```cpp
> //! Convert the solution with Taylor basis to the solution with Dubiner basis
> std::vector< std::vector< tk::real > >
> TransformTaylorToDubiner(
> ```

Same for this one.
___
*[src/PDE/Integrate/Basis.cpp, line 809 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5zGte4ggy0hs37tW6:-Mekqjd95oS84YxcZSU-:b-w2orfj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Integrate/Basis.cpp#L809)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

`ndof` will not be 1 here since the finite volume does not require limiter  and this function will not be called.
Just add a assert to make sure ndof > 1.
</blockquote></details>

Let's not assume that _this function will not be called_ and try to write correct code. This is easy to ensure. See above.
___
*[src/PDE/Integrate/Basis.cpp, line 442 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknxiS2YvMXsUawGaD:-MeknxiS2YvMXsUawGaE:bpny5z) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L442)):*
> ```cpp
>     // Matrix to store the second order derivatives of basis functions in
>     // reference domain
>     tk::real d2Bdxi2[6][6] =
> ```

Why is this C-style and `d2Bdx2` C++-style?
___
*[src/PDE/Integrate/Basis.cpp, line 453 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekoIiV6KGnSeWl6WI-:-MekoIiX-CKTCwia3u_q:bp5fq46) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L453)):*
> ```cpp
>     // physical domain
>     std::array< std::array< tk::real, 6 >, 6 > d2Bdx2;
>     d2Bdx2.fill({0});
> ```

Is this to silence a compiler warning? What is your intention here?
___
*[src/PDE/Integrate/Basis.cpp, line 544 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpBre6yJ7jOx6EBYC:-MekpBrfAP7jLLjdhxVv:b1ujcf1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L544)):*
> ```cpp
> // *****************************************************************************
> {
>   Assert( ndof > 1, "Mismatch in number of degrees of freedom" );
> ```

This will let it pass if `ndof=2` or `ndof=3` which both will segfault below. I know you don't want this to be called with `ndof=2` and `ndof=3` and those make no sense from the viewpoint of the numerical method, but as a software, and by mistake, this is allowed, so let's catch the mistake. See below.
___
*[src/PDE/Integrate/Basis.cpp, line 553 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpO48AbA7o_Jbzl82:-MekpO48AbA7o_Jbzl83:bhm9bk8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L553)):*
> ```cpp
> 
>   L[0] = vol;
> ```

```c++
if (ndof > 1) {
   Assert( ndof == 4, "..." );
   L[1] = vol / 10.0;
   L[2] = vol * 3.0/10.0;
   L[3] = vol * 3.0/5.0;
}
```
___
*[src/PDE/Integrate/Basis.cpp, line 559 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpXTh4m2RToUaS7Qx:-MekpXTh4m2RToUaS7Qy:b-uenbu6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L559)):*
> ```cpp
> 
>   if(ndof > 4)
>   {
> ```

```c++
Assert( ndof == 10, "..." );
```


<!-- Sent from Reviewable.io -->

2021-07-16 20:59 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 44 of 47 files reviewed, 12 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 584 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeVQTEAEi45g-aMKuO_:-Mel1D1w0NDplEhAwih7:b39a2c9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L584)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, I think having it both passed and returning is confusing to read. I think if it is created here from scratch, it should be returned, and if we only modify it, it should be passed as non-const ref, but not both.
</blockquote></details>

Just change `unk` to non-const and modify it within the function.
___
*[src/PDE/Limiter.cpp, line 590 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Mea4aYX1bR3MSldftoj:-Mel1aro26dCQxGj-djV:br9yiet) ([raw file](https://github.com/quinoacomputing/quinoa/blob/177a4783226ab4027739ea295497d04b91ccbf03/src/PDE/Limiter.cpp#L590)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

It seems here that we are modifying the cell-avg too; which is left to the previous code to decide if they have modified it in `unk`. Instead, let's have the loop range as `for(std::size_t idof = 1; idof < rdof; idof++)`? That way it is absolutely clear that we do not modify the cell-avg.
</blockquote></details>

Yes, it should start as 1 and just fixed it. Thanks!
___
*[src/PDE/Integrate/Basis.hpp, line 79 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknIsG97Ht1mfXM-fv:-Mel2m7Z5pBfIhHxB3X4:beqzq7d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.hpp#L79)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Does it need the prefix `Transform`? Isn't it obvious based on the function name `DubinerToTaylor` that it is a transformation?
</blockquote></details>

I think shorter might be better. Just changed to `DubinerToTaylor`.
___
*[src/PDE/Integrate/Basis.hpp, line 90 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknZKZDjKtKEGbDDIH:-Mel2uSy5IvKdBGZALfj:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.hpp#L90)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same for this one.
</blockquote></details>

Done! Thanks!
___
*[src/PDE/Integrate/Basis.cpp, line 809 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me5zGte4ggy0hs37tW6:-Mel0Z8kDOTHIJDY0R4u:b-93f4dt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Integrate/Basis.cpp#L809)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's not assume that _this function will not be called_ and try to write correct code. This is easy to ensure. See above.
</blockquote></details>

Just added assert here and the assert for `ndof == 10` is above.
___
*[src/PDE/Integrate/Basis.cpp, line 442 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknxiS2YvMXsUawGaD:-MekwJ8HBMh4Us51u8a5:bz1mvo0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L442)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why is this C-style and `d2Bdx2` C++-style?
</blockquote></details>

At the beginning, I tried to initialize it in C++ style. And I got the same error as the one posted online (https://stackoverflow.com/questions/12844475/why-cant-simple-initialize-with-braces-2d-stdarray).
I found that it requires extra brackets and I think it will be clean to initialize in C++ style. If you want here to be C++ style and I could change it.
___
*[src/PDE/Integrate/Basis.cpp, line 453 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekoIiV6KGnSeWl6WI-:-MekwBcZ0j3eHDBBaX9R:bz4aatg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L453)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Is this to silence a compiler warning? What is your intention here?
</blockquote></details>

Do you mean why I am using `fill({0})`. I first gave it `fill(0)` and this does not work and then I found the post (https://stackoverflow.com/questions/43925899/fastest-way-to-initialize-a-template-2d-stdarray-to-0). So just fix it by giving `fill({0})`
___
*[src/PDE/Integrate/Basis.cpp, line 544 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpBre6yJ7jOx6EBYC:-Mel09nLAMlU4tHPgkqZ:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L544)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This will let it pass if `ndof=2` or `ndof=3` which both will segfault below. I know you don't want this to be called with `ndof=2` and `ndof=3` and those make no sense from the viewpoint of the numerical method, but as a software, and by mistake, this is allowed, so let's catch the mistake. See below.
</blockquote></details>

Done! Thanks!
___
*[src/PDE/Integrate/Basis.cpp, line 553 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpO48AbA7o_Jbzl82:-Mel0CAA5X9v79yr0Fo2:byf5gpw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L553)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

```c++
if (ndof > 1) {
   Assert( ndof == 4, "..." );
   L[1] = vol / 10.0;
   L[2] = vol * 3.0/10.0;
   L[3] = vol * 3.0/5.0;
}
```
</blockquote></details>

Just add Assert here. However we cannot just make it equals to 4 since 10 could also be allowed here.
___
*[src/PDE/Integrate/Basis.cpp, line 559 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpXTh4m2RToUaS7Qx:-Mel0E3ACp8Ts9nmsRvw:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L559)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

```c++
Assert( ndof == 10, "..." );
```
</blockquote></details>

Done! Thanks!


<!-- Sent from Reviewable.io -->

2021-07-16 21:00 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 44 of 47 files reviewed, 12 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Integrate/Basis.cpp, line 442 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknxiS2YvMXsUawGaD:-Mel6fmq7ua_jmDetAbd:b3nzsej) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L442)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

At the beginning, I tried to initialize it in C++ style. And I got the same error as the one posted online (https://stackoverflow.com/questions/12844475/why-cant-simple-initialize-with-braces-2d-stdarray).
I found that it requires extra brackets and I think it will be clean to initialize in C++ style. If you want here to be C++ style and I could change it.
</blockquote></details>

Typo here. I think it is clean to initialize in C-style here.


<!-- Sent from Reviewable.io -->

2021-07-16 21:37 UTC, jbakosi requested changes
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 46 of 47 files reviewed, 8 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Integrate/Basis.cpp, line 442 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknxiS2YvMXsUawGaD:-MelDz5q7dE_uy9tM2r-:bw7h1im) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L442)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Typo here. I think it is clean to initialize in C-style here.
</blockquote></details>

Okay, so you want C or C++-style array? Either way is fine, but why different?
___
*[src/PDE/Integrate/Basis.cpp, line 453 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekoIiV6KGnSeWl6WI-:-MelCvUJ7dJSZIGev_wB:b-x649v7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L453)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Do you mean why I am using `fill({0})`. I first gave it `fill(0)` and this does not work and then I found the post (https://stackoverflow.com/questions/43925899/fastest-way-to-initialize-a-template-2d-stdarray-to-0). So just fix it by giving `fill({0})`
</blockquote></details>

I mean why do you need to initialize it here at all? Why don't you just zero the single entry immediately before computing? E.g.,
```c++
    for(std::size_t ibasis = 0; ibasis < 6; ibasis++) {
      for(std::size_t idir = 0; idir < 6; idir++) {
        d2Bdx2[idir][ibasis] = 0;
        for(std::size_t k = 0; k < 6; k++)
          d2Bdx2[idir][ibasis] += d2xdxi2[idir][k] * d2Bdxi2[k][ibasis];
      }
    }
```

And also declare it immediately before you use it, instead of here.
___
*[src/PDE/Integrate/Basis.cpp, line 553 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekpO48AbA7o_Jbzl82:-MelE_j56Q241B4RJ6Sc:b-2uv1uy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L553)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just add Assert here. However we cannot just make it equals to 4 since 10 could also be allowed here.
</blockquote></details>

You are correct.
___
*[src/PDE/Integrate/Basis.cpp, line 457 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MelDswc4om8Ipyam8l3:-MelDswc4om8Ipyam8l4:bfryv6s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/59afddd140b7647617ad6309dd46f44fdd5c8ccb/src/PDE/Integrate/Basis.cpp#L457)):*
> ```cpp
>     // function in reference domain to the one in physical domain
>     std::array< std::array< tk::real, 6 >, 6 > d2xdxi2;
>     d2xdxi2.fill({0});
> ```

Same here as above.


<!-- Sent from Reviewable.io -->

2021-07-16 23:07 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 45 of 47 files reviewed, 8 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Integrate/Basis.cpp, line 442 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MeknxiS2YvMXsUawGaD:-MelXz2G6i4JsT81IEOb:b-ijjcrm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L442)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Okay, so you want C or C++-style array? Either way is fine, but why different?
</blockquote></details>

Oh, I just realize that I changed one to C-style and forgot to change the other two matrix to C-style.
Just fixed this. Let me know whether this looks good or not.
___
*[src/PDE/Integrate/Basis.cpp, line 453 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MekoIiV6KGnSeWl6WI-:-MelWOPyBmWQrc0zxoBc:b-40f83c) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ede6854010eceddfadc85293eb69f2c1ecb93bf3/src/PDE/Integrate/Basis.cpp#L453)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I mean why do you need to initialize it here at all? Why don't you just zero the single entry immediately before computing? E.g.,
```c++
    for(std::size_t ibasis = 0; ibasis < 6; ibasis++) {
      for(std::size_t idir = 0; idir < 6; idir++) {
        d2Bdx2[idir][ibasis] = 0;
        for(std::size_t k = 0; k < 6; k++)
          d2Bdx2[idir][ibasis] += d2xdxi2[idir][k] * d2Bdxi2[k][ibasis];
      }
    }
```

And also declare it immediately before you use it, instead of here.

</blockquote></details>

Just removed the initialization.
Previously I thought both work fine and just put the `fill` function.
___
*[src/PDE/Integrate/Basis.cpp, line 457 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-MelDswc4om8Ipyam8l3:-MelWiaC3LHKCnOEiGPN:b7ccyjo) ([raw file](https://github.com/quinoacomputing/quinoa/blob/59afddd140b7647617ad6309dd46f44fdd5c8ccb/src/PDE/Integrate/Basis.cpp#L457)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same here as above.
</blockquote></details>

Yes, `d2xdxi2` does not necessarily require this initialization. Just removed this one.


<!-- Sent from Reviewable.io -->

2021-07-20 14:12 UTC, adityakpandare approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, 2 of 29 files at r9.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mf3FmAtCrgztQizxpPa:bnfp4nl)* status: 20 of 47 files reviewed, 6 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 556 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me61CVO6-eCg9mnanaK:-Mf3EQUCBv41ZHcFyQey:b-1hr2tg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L556)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Sure. What do you think @adityakpandare ?
</blockquote></details>

It should be consistent with what we rename `WENOFunction()` to. I am inclining towards: `WENOLimiting()` and `VertexBasedLimiting()`.
___
*[src/PDE/Limiter.cpp, line 731 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63FUz6jzTCFtWJkkE:-Mf3ExnLBMKD7WDJ-8wf:b-m9k4qq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L731)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I vote for the shortest. ;-)
</blockquote></details>

Consistent with `VertexBasedLimiting()`, we should call this `WENOLimiting()`.


<!-- Sent from Reviewable.io -->

2021-07-20 15:28 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496)* status: 18 of 47 files reviewed, 6 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 556 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me61CVO6-eCg9mnanaK:-Mf3WjaC9lMDUlWRiC_j:b-ughm87) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L556)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

It should be consistent with what we rename `WENOFunction()` to. I am inclining towards: `WENOLimiting()` and `VertexBasedLimiting()`.
</blockquote></details>

Just changed `WENOFunction`, `SuperbeeFunction` and `VertexBasedFunction` to `WENOLimiting`, `SuperbeeLimiting` and `VertexBasedLimiting`. Thank you!
___
*[src/PDE/Limiter.cpp, line 731 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-Me63FUz6jzTCFtWJkkE:-Mf3X0jO9GlVv3RF-bEF:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a8629d1bbd3d57c04b9dd018c502304ebc214857/src/PDE/Limiter.cpp#L731)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Consistent with `VertexBasedLimiting()`, we should call this `WENOLimiting()`.
</blockquote></details>

Done! Thanks!


<!-- Sent from Reviewable.io -->

2021-07-20 17:10 UTC, jbakosi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, 27 of 29 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mf3tLw28Uxw1p8_mS3W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-07-20 17:23 UTC, WeizhaoLi2018 reviewed
Thanks for the review! I will merge this into develop once it passes the online test.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mf3wFB36DYj3c9fHgCl:b-f5c6nc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-07-20 17:25 UTC, jbakosi approved these changes
Sounds good. Don't wait for other PRs.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/496#-:-Mf3wgrdEQbLXbqMvZqW:bxhbimx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-07-24 13:03 UTC, merged