Minor fix
quinoacomputing/quinoa pull request #524
Opened 2021-10-29 22:00 UTC by WeizhaoLi2018

This PR removes NodalExtrem for DGP1 and P0P1 since it is not necessary here.
It also adds the cmark in reconstruction function

2021-11-02 17:58 UTC, adityakpandare requested changes
Thanks for correcting the indexing in Reconstruction. I have a few other comments.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-:-MnWnHRKDQ8m9sZbFbT2:b-6nra4v)* status: all files reviewed, 5 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl3ooAQjhDN4g2IZy:-MnWl3ooAQjhDN4g2IZz:b-77ek7c) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/Inciter/DG.cpp#L57)):*
> ```cpp
>         const std::vector< std::size_t >& triinpoel ) :
>   m_disc( disc ),
>   m_ndof_NodalExtrm( 3 ),
> ```

Just to clarify, this "3" corresponds to the 3 high-order DOFs, right?
___
*[src/PDE/Limiter.cpp, line 1050 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmeOY-7hrwOwkjmJQ:-MnWmeOY-7hrwOwkjmJR:b-ikemi7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Limiter.cpp#L1050)):*
> ```cpp
>         auto cmark = c-VarRange[0];
>         uMin[cmark] = std::min(uMin[cmark], U(er, mark, offset));
>         uMax[cmark] = std::max(uMax[cmark], U(er, mark, offset));
> ```

This code assumes that the node-neighbor solution data has been communicated; is that correct?
___
*[src/PDE/Limiter.cpp, line 1231 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmwL-2_SIYgMYi4u-:-MnWmwL-2_SIYgMYi4u0:bpn94rs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Limiter.cpp#L1231)):*
> ```cpp
>           auto max_mark = 2*c*ndof_NodalExtrm + 2*idir;
>           auto min_mark = max_mark + 1;
>           uMax[c][idir-1] =
> ```

Here, `idir-1` will be -1, when `idir` is 0. That will index out of `uMax` and `uMin`, causing a seg-fault.
___
*[src/PDE/Reconstruction.cpp, line 372 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmE3-Es1LglaWAJ9G:-MnWmE3-Es1LglaWAJ9H:baavczo) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Reconstruction.cpp#L372)):*
> ```cpp
>       {
>         auto mark = c*rdof;
>         auto cmark = c - varRange[0];
> ```

Thanks for correcting this!
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 746 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWm2zv-Z3UyuzWuv2M:-MnWm2zv-Z3UyuzWuv2N:bld0768) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/MultiMat/DGMultiMat.hpp#L746)):*
> ```cpp
>                 [[maybe_unused]] const std::vector< std::vector<tk::real> >&
>                   uNodalExtrm,
>                 [[maybe_unused]] const std::vector< std::vector<tk::real> >&
> ```

See comment in DGTransport.
___
*[src/PDE/Transport/DGTransport.hpp, line 281 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl_LL0_BPNWmnzr2c:-MnWl_LL0_BPNWmnzr2d:bl5pvc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Transport/DGTransport.hpp#L281)):*
> ```cpp
>                   std::unordered_map< std::size_t, std::size_t >& bid,
>                 [[maybe_unused]] const std::vector< std::vector<tk::real> >&
>                   uNodalExtrm,
> ```

if `gid`, `bid` and `unodalextrm` are not used, let's modify these arguments as:
`const std::vector< std::size_t >&,`, etc. The `[[maybe_unused]]` keyword is used when certain builds (debug) use the arguments, and the others (release) do not use them.


<!-- Sent from Reviewable.io -->

2021-11-02 19:08 UTC, jbakosi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 5 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 1231 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmwL-2_SIYgMYi4u-:-MnX1qMIDwuXUNoWcmZ-:b-tbjkek) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Limiter.cpp#L1231)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Here, `idir-1` will be -1, when `idir` is 0. That will index out of `uMax` and `uMin`, causing a seg-fault.
</blockquote></details>

And since `idir` is unsigned, it will just be a very large number, still causing a segfault.


<!-- Sent from Reviewable.io -->

2021-11-03 02:15 UTC, WeizhaoLi2018 reviewed
Thanks for the review! I just pushed the new commit according to the suggestions.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-:-MnYOBLWCogv7uwpakcm:baix1ck)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @adityakpandare)

___
*[src/Inciter/DG.cpp, line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl3ooAQjhDN4g2IZy:-MnYM_Oa9dcZIEVq7mnT:b-d8wgir) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/Inciter/DG.cpp#L57)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Just to clarify, this "3" corresponds to the 3 high-order DOFs, right?
</blockquote></details>

Yes, it corresponds to 3 high-order DOFs. Or specifically, it represents the three directions of first order derivatives.
___
*[src/PDE/Limiter.cpp, line 1050 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmeOY-7hrwOwkjmJQ:-MnYMt8PB-H-P1vuLeg8:bbbemz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Limiter.cpp#L1050)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This code assumes that the node-neighbor solution data has been communicated; is that correct?
</blockquote></details>

Yes, it is correct.
___
*[src/PDE/Limiter.cpp, line 1231 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWmwL-2_SIYgMYi4u-:-MnYN3ik3IqVeSRwApfd:bkia033) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Limiter.cpp#L1231)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

And since `idir` is unsigned, it will just be a very large number, still causing a segfault.
</blockquote></details>

Thanks for pointing out this. I changed the loop condition but forgot to check the index part.
Thank you, guys!
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 746 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWm2zv-Z3UyuzWuv2M:-MnYNhvAB4NLhPcr78MV:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/MultiMat/DGMultiMat.hpp#L746)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

See comment in DGTransport.
</blockquote></details>

Done! Thank you!
___
*[src/PDE/Transport/DGTransport.hpp, line 281 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl_LL0_BPNWmnzr2c:-MnYO8IJAb2L-k7WBzWV:b-synsn8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/PDE/Transport/DGTransport.hpp#L281)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

if `gid`, `bid` and `unodalextrm` are not used, let's modify these arguments as:
`const std::vector< std::size_t >&,`, etc. The `[[maybe_unused]]` keyword is used when certain builds (debug) use the arguments, and the others (release) do not use them.
</blockquote></details>

Got it! Done! Thank you!


<!-- Sent from Reviewable.io -->

2021-11-03 02:44 UTC, adityakpandare requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 3 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 730 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnYfEha5cGkpz_BPE7p:-MnYfEha5cGkpz_BPE7q:bgzfpoz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32dc6f307ae78bcb9decf153a681b77bd7a2a8a8/src/PDE/MultiMat/DGMultiMat.hpp#L730)):*
> ```cpp
>     //!   variables
>     //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
>     //!   variables
> ```

We'll have to remove the comments for gid, bid, etc which have been removed from the arguments (I believe some tests fail if there are comments for arguments that are not used). Unless they are going to be needed again, in which case, just comment the comments like:
```
//   //! \param[in] gid Local->global node id map
```
___
*[src/PDE/Transport/DGTransport.hpp, line 266 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnYfXZ80kRwT-_zXqwf:-MnYfXZ80kRwT-_zXqwg:b-mcugvx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32dc6f307ae78bcb9decf153a681b77bd7a2a8a8/src/PDE/Transport/DGTransport.hpp#L266)):*
> ```cpp
>     //! \param[in] uNodalExtrm Chare-boundary nodal extrema for conservative
>     //!   variables
>     //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
> ```

Same here about commenting the comments, so that tests pass.


<!-- Sent from Reviewable.io -->

2021-11-03 03:25 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 730 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnYfEha5cGkpz_BPE7p:-MnYnprS8Qu7wikVKEag:b8895m4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32dc6f307ae78bcb9decf153a681b77bd7a2a8a8/src/PDE/MultiMat/DGMultiMat.hpp#L730)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We'll have to remove the comments for gid, bid, etc which have been removed from the arguments (I believe some tests fail if there are comments for arguments that are not used). Unless they are going to be needed again, in which case, just comment the comments like:
```
//   //! \param[in] gid Local->global node id map
```
</blockquote></details>

Just added the comment. Let me know if this works or not.
Thank you!


<!-- Sent from Reviewable.io -->

2021-11-03 15:02 UTC, adityakpandare approved these changes
Tests pass. Thanks! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-:-MnaJiBx8gpLkT_m_sCj:b-3h6zfp)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/Transport/DGTransport.hpp, line 266 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnYfXZ80kRwT-_zXqwf:-MnaJ5gy8cferrtqwBLf:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32dc6f307ae78bcb9decf153a681b77bd7a2a8a8/src/PDE/Transport/DGTransport.hpp#L266)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same here about commenting the comments, so that tests pass.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2021-11-03 16:15 UTC, jbakosi requested changes
> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 10 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl3ooAQjhDN4g2IZy:-MnaV7sW6PKNecEQYR48:b6xjisr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/Inciter/DG.cpp#L57)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Yes, it corresponds to 3 high-order DOFs. Or specifically, it represents the three directions of first order derivatives.
</blockquote></details>

Since this was a question even for @adityakpandare (let alone for me), maybe a comment on this is in order, e.g.,
```cpp
 m_ndof_NodalExtrm( 3 ),  // for the 3 first derivatives in three directions
```
or something similar.
___
*[src/Inciter/DG.cpp, line 2017 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaVnHw63aA2VWO9o97:-MnaVnHw63aA2VWO9o98:b87uuip) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2017)):*
> ```cpp
>           gradc(ncomp, std::vector<tk::real>(3, 0.0));
>         std::vector< std::vector< tk::real > >
>           gradp(ncomp, std::vector<tk::real>(3, 0.0));
> ```

Since the inner vector length is always 3, does it make more sense to use a `std::array` of 3 reals instead?
___
*[src/Inciter/DG.cpp, line 2075 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaWbnP11D0ZN9KRD6w:-MnaWbnP11D0ZN9KRD6x:b-a6m6kv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2075)):*
> ```cpp
>             uNodalExtrm[i->second][min_mark] =
>               std::min(uNodalExtrm[i->second][min_mark], gradc[c][idof-1]);
>           }
> ```

This could be shortened:
```cpp
auto& ex = uNodalExtrm[i->second];
ex[max_mark] = std::max(ex[max_mark], gradc[c][idof-1]);
ex[min_mark] = std::min(ex[min_mark], gradc[c][idof-1]);

```
___
*[src/Inciter/DG.cpp, line 2086 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaX3rg9xKsO_4yj99d:-MnaX3rg9xKsO_4yj99e:b-jvhko6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2086)):*
> ```cpp
>               std::max(pNodalExtrm[i->second][max_mark], gradp[c][idof-1]);
>             pNodalExtrm[i->second][min_mark] =
>               std::min(pNodalExtrm[i->second][min_mark], gradp[c][idof-1]);
> ```

Same as above. Easier to read shorter code.
___
*[src/PDE/Limiter.cpp, line 1234 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaXMPzDtlN8QLYR39D:-MnaXMPzDtlN8QLYR39E:bxr18f3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Limiter.cpp#L1234)):*
> ```cpp
>             std::max(NodalExtrm[gip->second][max_mark], uMax[c][idir]);
>           uMin[c][idir] =
>             std::min(NodalExtrm[gip->second][min_mark], uMin[c][idir]);
> ```

You could put `NodalExtrm[gip->second]` to a `auto&` as above to shorten this too.
___
*[src/PDE/Reconstruction.cpp, line 348 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZ0le7I6lzjixXUqm:-MnaZ0le7I6lzjixXUqn:b-6d22gy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L348)):*
> ```cpp
>   std::vector< std::array< tk::real, 3 > >
>   rhs_ls( varRange[1]-varRange[0]+1, {{ 0.0, 0.0, 0.0 }} );
> ```

```cpp
Assert( varRange[0] < varRange[1], " ... " );
Assert( varRange[1] - varRange[0] + 1 < lhs_ls.size(), " ... " );
```
___
*[src/PDE/Reconstruction.cpp, line 369 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaYZqq4G_a2GUZCMkK:-MnaYZqrBIx8tnJkyxG6:bptmajy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L369)):*
> ```cpp
> 
>       // compute rhs matrix
>       for (std::size_t c=varRange[0]; c<=varRange[1]; ++c)
> ```

Are we sure we want inclusive upper bound here? If so, should we instead use the C/C++ convention and require client code to specify bounds as lower-inclusive and upper-exclusive? (And then write the loop as ```for (std::size_t c=varRange[0]; c<varRange[1]; ++c)```.)
___
*[src/PDE/CompFlow/DGCompFlow.hpp, line 295 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZm-45q102FSsUcv5:-MnaZm-45q102FSsUcv6:bx84cd0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/CompFlow/DGCompFlow.hpp#L295)):*
> ```cpp
>     //!   variables
> //    //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
> //    //!   variables
> ```

Let's remove the doxy comments if there is no need for them.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 730 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZuiC8eDWei8VbUuf:-MnaZuiC8eDWei8VbUug:bx84cd0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/MultiMat/DGMultiMat.hpp#L730)):*
> ```cpp
> //    //!   variables
> //    //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
> //    //!   variables
> ```

Let's remove the doxy comments if there is no need for them.
___
*[src/PDE/Transport/DGTransport.hpp, line 267 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZyQ_4YcTmpxQ6U6M:-MnaZyQ_4YcTmpxQ6U6N:bx84cd0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Transport/DGTransport.hpp#L267)):*
> ```cpp
> //    //!   variables
> //    //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
> //    //!   variables
> ```

Let's remove the doxy comments if there is no need for them.


<!-- Sent from Reviewable.io -->

2021-11-03 16:27 UTC, adityakpandare approved these changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 10 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 369 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaYZqq4G_a2GUZCMkK:-Mnab4kNCG8iXXApQRB8:b-t8nrea) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L369)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Are we sure we want inclusive upper bound here? If so, should we instead use the C/C++ convention and require client code to specify bounds as lower-inclusive and upper-exclusive? (And then write the loop as ```for (std::size_t c=varRange[0]; c<varRange[1]; ++c)```.)
</blockquote></details>

The reason I suggested @weizhaoli2018 to write it this way is that the client code is more intuitive: i.e. the client code can specify the exact range of variables for which reconstruction is to be performed, rather than having the client code to specify range+1. I vote for keeping this the way it is, i.e. with the upper-bound inclusive.
___
*[src/PDE/CompFlow/DGCompFlow.hpp, line 295 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZm-45q102FSsUcv5:-MnabmVY30XJHW5gJJB7:b-ngkqy1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/CompFlow/DGCompFlow.hpp#L295)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's remove the doxy comments if there is no need for them.
</blockquote></details>

I suggested to comment them rather than removing, because I suspect @weizhaoli2018 will be needing them for the dgp2-multimat capability. I don't mind removing them though.


<!-- Sent from Reviewable.io -->

2021-11-03 16:42 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 10 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 369 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaYZqq4G_a2GUZCMkK:-Mnaelrz5J4LBiTR56ar:bu9e7k0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L369)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The reason I suggested @weizhaoli2018 to write it this way is that the client code is more intuitive: i.e. the client code can specify the exact range of variables for which reconstruction is to be performed, rather than having the client code to specify range+1. I vote for keeping this the way it is, i.e. with the upper-bound inclusive.
</blockquote></details>

I agree with @adityakpandare. It is more intuitive for reading the code.
But if inclusive upper bound is the issue, how about we use `for (std::size_t c=varRange[0]; c<varRange[1]+1; ++c)`.


<!-- Sent from Reviewable.io -->

2021-11-03 16:42 UTC, jbakosi reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 369 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaYZqq4G_a2GUZCMkK:-MnaewYkEv0K2g-lhOg7:bc1rghw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L369)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The reason I suggested @weizhaoli2018 to write it this way is that the client code is more intuitive: i.e. the client code can specify the exact range of variables for which reconstruction is to be performed, rather than having the client code to specify range+1. I vote for keeping this the way it is, i.e. with the upper-bound inclusive.
</blockquote></details>

Okay, that's convincing and makes sense, depending which sunglasses I wear: those of a computer scientist or those of a computational scientist. ;-)
(Let's keep it.)
___
*[src/PDE/CompFlow/DGCompFlow.hpp, line 295 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZm-45q102FSsUcv5:-MnafLV22hiYN4IxXG_V:bnzpa9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/CompFlow/DGCompFlow.hpp#L295)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I suggested to comment them rather than removing, because I suspect @weizhaoli2018 will be needing them for the dgp2-multimat capability. I don't mind removing them though.
</blockquote></details>

Okay, that makes sense. If we are sure we will need them in the near future, then let's just keep them.


<!-- Sent from Reviewable.io -->

2021-11-03 16:44 UTC, jbakosi reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 369 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaYZqq4G_a2GUZCMkK:-MnafoGTE2C0nFJ5f9_j:b-a50yde) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L369)):*
> ```cpp
> for (std::size_t c=varRange[0]; c<varRange[1]+1; ++c)
> ```

There is no need for this. Let's just keep it as it is.


<!-- Sent from Reviewable.io -->

2021-11-03 20:07 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl3ooAQjhDN4g2IZy:-MnbDYOfBT3Jqn22MNLg:bgfdy3f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/Inciter/DG.cpp#L57)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Since this was a question even for @adityakpandare (let alone for me), maybe a comment on this is in order, e.g.,
```cpp
 m_ndof_NodalExtrm( 3 ),  // for the 3 first derivatives in three directions
```
or something similar.
</blockquote></details>

Just added. Thank you!
___
*[src/Inciter/DG.cpp, line 2017 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaVnHw63aA2VWO9o97:-MnbFEpi-t0aLK_aAZgz:byy3h7g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2017)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Since the inner vector length is always 3, does it make more sense to use a `std::array` of 3 reals instead?
</blockquote></details>

Yes, just covert it to `array`.
___
*[src/Inciter/DG.cpp, line 2075 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaWbnP11D0ZN9KRD6w:-MnbFzF_6nM0TiIMMCdl:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2075)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This could be shortened:
```cpp
auto& ex = uNodalExtrm[i->second];
ex[max_mark] = std::max(ex[max_mark], gradc[c][idof-1]);
ex[min_mark] = std::min(ex[min_mark], gradc[c][idof-1]);

```
</blockquote></details>

Done! Thanks!
___
*[src/Inciter/DG.cpp, line 2086 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaX3rg9xKsO_4yj99d:-MnbG-beD8lbgHnbLgJa:b-cmt4a6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/Inciter/DG.cpp#L2086)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same as above. Easier to read shorter code.
</blockquote></details>

Done! Thanks!
___
*[src/PDE/Limiter.cpp, line 1234 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaXMPzDtlN8QLYR39D:-MnbGNM3EyWbt5WRSjL1:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Limiter.cpp#L1234)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

You could put `NodalExtrm[gip->second]` to a `auto&` as above to shorten this too.
</blockquote></details>

Done! Thank you!
___
*[src/PDE/Reconstruction.cpp, line 348 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZ0le7I6lzjixXUqm:-MnbHQGk5M85a9FOGciU:bhmasf0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L348)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

```cpp
Assert( varRange[0] < varRange[1], " ... " );
Assert( varRange[1] - varRange[0] + 1 < lhs_ls.size(), " ... " );
```
</blockquote></details>

Just added the first assert as suggested. I think we don't need the second assert because we solve the linear system here as:

``` c++
auto ux = tk::cramer( lhs_ls, rhs_ls[cmark] );
```

And rhs_ls[cmark] is always an array with size of 3.
___
*[src/PDE/CompFlow/DGCompFlow.hpp, line 295 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZm-45q102FSsUcv5:-MnbIpwf82vs07HejNci:b-8mjhit) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/CompFlow/DGCompFlow.hpp#L295)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Okay, that makes sense. If we are sure we will need them in the near future, then let's just keep them.
</blockquote></details>

We will still need `gid` and `bid` for P2 limiting. While `pNodalExtrm` should be useless for P2 limiting in Transport and Compflow. So I just removed the comments for `pNodalExtrm`. Thanks!


<!-- Sent from Reviewable.io -->

2021-11-03 20:13 UTC, jbakosi requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 3 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnWl3ooAQjhDN4g2IZy:-MnbP4yq-2wXnGsyrhFH:bhtv32p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9f3dace2c2d6ddd2822905548fcab45b8598da70/src/Inciter/DG.cpp#L57)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Since this was a question even for @adityakpandare (let alone for me), maybe a comment on this is in order, e.g.,
```cpp
 m_ndof_NodalExtrm( 3 ),  // for the 3 first derivatives in three directions
```
or something similar.
</blockquote></details>

Thanks, I like your wording better than mine! ;-)
___
*[src/PDE/Reconstruction.cpp, line 348 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZ0le7I6lzjixXUqm:-MnbPZb3DWsVYMO1Rwj_:b7mozwz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L348)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just added the first assert as suggested. I think we don't need the second assert because we solve the linear system here as:

``` c++
auto ux = tk::cramer( lhs_ls, rhs_ls[cmark] );
```

And rhs_ls[cmark] is always an array with size of 3.
</blockquote></details>

Right, but the assert detects problems with the incoming variable ranges. Say` varRange = [1, 14]`. What happens then? Segfault? There is a loop below that spans `varRange` and indexes `rhs_ls`. If so, I would prefer an assert -> exception with an error message. (The assert can be: ```Assert( varRange[1] - varRange[0] + 1 < rhs_ls.size(), " ... " );```.)


<!-- Sent from Reviewable.io -->

2021-11-03 21:22 UTC, WeizhaoLi2018 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 3 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 348 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZ0le7I6lzjixXUqm:-MnbdLTnAogtVEAb6bwB:b-chqm3x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L348)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Right, but the assert detects problems with the incoming variable ranges. Say` varRange = [1, 14]`. What happens then? Segfault? There is a loop below that spans `varRange` and indexes `rhs_ls`. If so, I would prefer an assert -> exception with an error message. (The assert can be: ```Assert( varRange[1] - varRange[0] + 1 < rhs_ls.size(), " ... " );```.)
</blockquote></details>

I don't understand here. If we look at how we define `rhs_ls`:

```c++
  std::vector< std::array< tk::real, 3 > >  rhs_ls( varRange[1]-varRange[0]+1, {{ 0.0, 0.0, 0.0 }} );
```

The size of `rhs_ls` is already `varRange[1] - varRange[0] + 1`. Why do we need `Assert( varRange[1] - varRange[0] + 1 < rhs_ls.size(), " ... " )`?
Also, when `varRange = [1,14]`, this means that we will solve `14`linear systems and the size of each linear system will be `3x3`. `lhs_ls` is the `3x3` matrix for all the linear systems. While `rhs_ls[cmark]` (array with size of 3) is the right-hand-side for each linear system. I didn't see any segfault here.


<!-- Sent from Reviewable.io -->

2021-11-03 22:07 UTC, jbakosi reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 348 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/524#-MnaZ0le7I6lzjixXUqm:-MnbplJR7MQFgOOIIsLK:b-jjujm9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd451e6f4e2137b395a5fbde94076751db52901e/src/PDE/Reconstruction.cpp#L348)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I don't understand here. If we look at how we define `rhs_ls`:

```c++
  std::vector< std::array< tk::real, 3 > >  rhs_ls( varRange[1]-varRange[0]+1, {{ 0.0, 0.0, 0.0 }} );
```

The size of `rhs_ls` is already `varRange[1] - varRange[0] + 1`. Why do we need `Assert( varRange[1] - varRange[0] + 1 < rhs_ls.size(), " ... " )`?
Also, when `varRange = [1,14]`, this means that we will solve `14`linear systems and the size of each linear system will be `3x3`. `lhs_ls` is the `3x3` matrix for all the linear systems. While `rhs_ls[cmark]` (array with size of 3) is the right-hand-side for each linear system. I didn't see any segfault here.
</blockquote></details>

Ah, you are right. There is no need to assert the obvious.


<!-- Sent from Reviewable.io -->

2021-11-04 16:06 UTC, adityakpandare approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/524)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2021-11-04 23:53 UTC, merged