Replace eos_pressure calls with new EOS framework
quinoacomputing/quinoa pull request #544
Opened 2022-04-06 17:00 UTC by TannerNielsen

2022-04-06 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/quinoacomputing/quinoa?pullRequest=544) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/quinoacomputing/quinoa?pullRequest=544) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: adityakpandare<br/>:x: TannerNielsen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/quinoacomputing/quinoa?pullRequest=544) it.</sub>

2022-04-06 20:19 UTC, adityakpandare requested changes
Nice! Thanks @tannernielsen for persisting with these changes! I have a few comments below: most of them are cosmetic. Once those are addressed, this can be merged.

> Reviewed 53 of 53 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-:-N--Wf6SAXHiXFvukR-Q:b-mzl6bk)* status: all files reviewed, 64 unresolved discussions (waiting on @TannerNielsen)

___
*[src/PDE/ConfigureCompFlow.hpp, line 25 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Nf2n17xfj2w6URDI:-N--Nf2n17xfj2w6URDJ:b-e91xrx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/ConfigureCompFlow.hpp#L25)):*
> ```cpp
> #include "ContainerUtil.hpp"
> #include "EoS/EoS.hpp"
> #include "EoS/EoS_Base.hpp"
> ```

Since we're not using the new `EoS_Base` class here, can we remove this include?
___
*[src/PDE/DGPDE.hpp, line 76 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--NxDYEifTldQYLAcM:-N--NxDYEifTldQYLAcN:bmdbi3d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/DGPDE.hpp#L76)):*
> ```cpp
>            tk::real, tk::real, tk::real, tk::real,
>            const std::array< tk::real, 3> &,
>            const std::vector< EoS_Base* >& m_mat_blk );
> ```

The argument name (`m_mat_blk`) is not needed here. Let's remove it. Also, for future reference, the naming convention "m_" is used only for class members, not other.
___
*[src/PDE/FunctionPrototypes.hpp, line 55 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Ostk6Dg1RdqVwZqM:-N--Ostk6Dg1RdqVwZqN:bw43kx3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/FunctionPrototypes.hpp#L55)):*
> ```cpp
> using FluxFn = std::function<
>   std::vector< std::array< real, 3 > >
>   ( ncomp_t, ncomp_t, const std::vector< inciter::EoS_Base* >&, 
> ```

Sorry for nitpicking, but can we remove the extra whitespace at the end of the line above?
___
*[src/PDE/Limiter.cpp, line 26 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--PBQsByxc80lNqDH3:-N--PBQsByxc80lNqDH4:bmdb2sl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Limiter.cpp#L26)):*
> ```cpp
> #include "Inciter/InputDeck/InputDeck.hpp"
> #include "EoS/EoS.hpp"
> #include "EoS/StiffenedGas.hpp"
> ```

Do we need to include `StiffenedGas.hpp` here? If not, we should remove it.
___
*[src/PDE/Limiter.cpp, line 27 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Pecb1Ni8nkeyRpRA:-N--Pecb1Ni8nkeyRpRB:bhdtf8g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Limiter.cpp#L27)):*
> ```cpp
> #include "EoS/EoS.hpp"
> #include "EoS/StiffenedGas.hpp"
> #include "EoS/MatBlock.hpp"
> ```

Let's remove this file since it's not being used.
___
*[src/PDE/Reconstruction.hpp, line 57 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Pvn01wbL4inbnprJ:-N--Pvn01wbL4inbnprK:b-sct90d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Reconstruction.hpp#L57)):*
> ```cpp
>   ncomp_t ncomp,
>   ncomp_t offset,
>   const std::vector< inciter::EoS_Base* >& m_mat_blk,
> ```

`m_` is only used for class members. Since this is not a class, and `mat_blk` is not it's member, could you rename it?
___
*[src/PDE/Reconstruction.hpp, line 68 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--PnHaC7_6nz2uaHJ1:-N--PnHaC7_6nz2uaHJ2:bixpp9w) ([raw file](https://github.com/quinoacomputing/quinoa/blob/89458150a41c6f5aea91d99035ef1cf9b5c26099/src/PDE/Reconstruction.hpp#L68)):*
> ```cpp
>   const std::array< std::size_t, 2 >& varRange,
>   std::size_t nprim=0 );
> ```

Let's not remove this empty line; it helps with discerning separate function declarations.
___
*[src/PDE/Reconstruction.cpp, line 255 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QGOMD1UjKziDw6dY:-N--QGOMD1UjKziDw6dZ:b-o82mcc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Reconstruction.cpp#L255)):*
> ```cpp
> 
>         // Compute the state at the face-center using BC
> //        std::vector< inciter::EoS_Base* > mat_blk;
> ```

Could we remove this commented code since it's not going to be used in the future?
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 84 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QNv546aEe0UQLp-E:-N--QNv546aEe0UQLp-F:bc9rqh0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L84)):*
> ```cpp
>       Assert( g_inputdeck.get< tag::component >().get< eq >().at(c) == m_ncomp,
>        "Number of CompFlow PDE components must be " + std::to_string(m_ncomp) );
>     
> ```

let's remove the whitespaces in the above line.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 236 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QZ277tet0nh0f3AK:-N--QZ277tet0nh0f3AL:bk85uft) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L236)):*
> ```cpp
>     std::vector< real >
>     analyticSolution( real xi, real yi, real zi, real t ) const
>     { return Problem::analyticSolution( m_system, m_ncomp, m_mat_blk, xi, yi, 
> ```

Let's remove the trailing whitespace in the above line.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 316 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qdly1EEgwinrH479:-N--Qdlz9Znqhg8PB0LE:b-s2crp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L316)):*
> ```cpp
>         std::array< real, 4 > p;
>         for (std::size_t a=0; a<4; ++a)
>           p[a] = m_mat_blk[0]->eos_pressure( m_system, u[0][a], u[1][a]/u[0][a], 
> ```

Same with the trailing whitespace here.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 375 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qepb778vdo72azFE:-N--Qepb778vdo72azFF:b-s2crp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L375)):*
> ```cpp
> 
>         // pressure
>         auto p = m_mat_blk[0]->eos_pressure( m_system, ue[0], ue[1]/ue[0], 
> ```

Same with the trailing whitespace here.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 649 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QgdIBB6v2nYPOPkb:-N--QgdIBB6v2nYPOPkc:b-s2crp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L649)):*
> ```cpp
>           auto& rw = u[3][j];    // rho * w
>           auto& re = u[4][j];    // rho * e
>           auto p = m_mat_blk[0]->eos_pressure( m_system, r, ru/r, rv/r, rw/r, 
> ```

Same with the trailing whitespace here.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 720 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qpjv6i3KELKTT7Q7:-N--Qpjv6i3KELKTT7Q8:b-s2crp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L720)):*
> ```cpp
>         const auto u = U[i];
>         // compute pressure
>         auto p = m_mat_blk[0]->eos_pressure( m_system, u[0], u[1]/u[0], 
> ```

Same with the trailing whitespace here.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 863 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QjNqDmzoaouLGAre:-N--QjNqDmzoaouLGArf:b-s2crp1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L863)):*
> ```cpp
>                     (ru*i->second[0] + rv*i->second[1] + rw*i->second[2]) / r;
>                   auto a = e [...]

2022-04-07 16:19 UTC, TannerNielsen reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/544)* status: 26 of 53 files reviewed, 64 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/ConfigureCompFlow.hpp, line 25 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Nf2n17xfj2w6URDI:-N-3HnVG0QMglYRen8ym:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/ConfigureCompFlow.hpp#L25)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Since we're not using the new `EoS_Base` class here, can we remove this include?
</blockquote></details>

Done.
___
*[src/PDE/DGPDE.hpp, line 76 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--NxDYEifTldQYLAcM:-N-3IGV53NNDgCwA5D9t:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/DGPDE.hpp#L76)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The argument name (`m_mat_blk`) is not needed here. Let's remove it. Also, for future reference, the naming convention "m_" is used only for class members, not other.
</blockquote></details>

Done.
___
*[src/PDE/FunctionPrototypes.hpp, line 55 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Ostk6Dg1RdqVwZqM:-N-3IbIO38Pxp_7KO35Q:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/FunctionPrototypes.hpp#L55)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Sorry for nitpicking, but can we remove the extra whitespace at the end of the line above?
</blockquote></details>

Done.
___
*[src/PDE/Limiter.cpp, line 26 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--PBQsByxc80lNqDH3:-N-3JpdgBb1bI7njhHPO:b-53nyac) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Limiter.cpp#L26)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Do we need to include `StiffenedGas.hpp` here? If not, we should remove it.
</blockquote></details>

I don't think it's needed here. Removed.
___
*[src/PDE/Limiter.cpp, line 27 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Pecb1Ni8nkeyRpRA:-N-3JLz8Cdn-Op0M_5k9:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Limiter.cpp#L27)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's remove this file since it's not being used.
</blockquote></details>

Done.
___
*[src/PDE/Reconstruction.hpp, line 57 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Pvn01wbL4inbnprJ:-N-3KvJ42CIS41sW-yI0:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Reconstruction.hpp#L57)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

`m_` is only used for class members. Since this is not a class, and `mat_blk` is not it's member, could you rename it?
</blockquote></details>

Done.
___
*[src/PDE/Reconstruction.hpp, line 68 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--PnHaC7_6nz2uaHJ1:-N-3Kvzc-xMve2os6I1O:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/89458150a41c6f5aea91d99035ef1cf9b5c26099/src/PDE/Reconstruction.hpp#L68)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's not remove this empty line; it helps with discerning separate function declarations.
</blockquote></details>

Done.
___
*[src/PDE/Reconstruction.cpp, line 255 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QGOMD1UjKziDw6dY:-N-3L3PyBpa3fSE8dPRK:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/Reconstruction.cpp#L255)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could we remove this commented code since it's not going to be used in the future?
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 84 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QNv546aEe0UQLp-E:-N-3LKOKE5gbNhE6j8iR:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L84)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

let's remove the whitespaces in the above line.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 236 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QZ277tet0nh0f3AK:-N-3LPVD86px9W7mRGZj:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L236)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's remove the trailing whitespace in the above line.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 316 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qdly1EEgwinrH479:-N-3LTkg8KFr1WhXCS9J:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L316)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with the trailing whitespace here.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 375 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qepb778vdo72azFE:-N-3Lbir6xMOjgxCYzOF:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L375)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with the trailing whitespace here.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 649 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QgdIBB6v2nYPOPkb:-N-3LfJU3arTuXGR5WUK:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L649)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with the trailing whitespace here.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 720 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qpjv6i3KELKTT7Q7:-N-3Lix239TaRNoNkfRa:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L720)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with the trailing whitespace here.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 863 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--QjNqDmzoaouLGAre:-N-3LmWz3Cr2AdQgTpL2:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L863)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with the trailing whitespace here.
</blockquote></details>

Done.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 880 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-N--Qr5y5vTRo90wG7WJ:-N-3M29fBzjmIih4IRG2:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e9b3fad0a136c8fd21a54c524a00fc48e45e728f/src/PDE/CompFlow/CGCompFlow.hpp#L880)):*
<details><summary><i>Previously, adit [...]

2022-04-07 20:49 UTC, adityakpandare approved these changes
Thanks. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/544#-:-N-42SVN5ogJEU5kfOcw:b3pjyss)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TannerNielsen)



<!-- Sent from Reviewable.io -->

2022-04-07 21:08 UTC, merged