limsol_projection for fv
quinoacomputing/quinoa pull request #552
Opened 2022-06-20 23:41 UTC by adityakpandare

Following changes:
1. adding the post-limiting projection to FV;
2. bug fix in this projection: In the previous version, nothing was changing for the p0p1/fv, since ndof was being used. Changed ndof to rdof appropriately in a few places in that function, since for reconstructed methods (like p0p1/fv), rdof needs to be used so that the reconstructed dofs get projected.

2022-06-20 23:46 UTC, WeizhaoLi2018 approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/552)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)



<!-- Sent from Reviewable.io -->

2022-06-21 00:05 UTC, WeizhaoLi2018 requested changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/552)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/Limiter.cpp` line 2786 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/552#-N52ZQyBAMgo51lInoov:-N52ZQyCBgfDjulkpg8-:b1tgwob) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dd5118d3ea194918a3ed8dfb1cf0997b3756805f/src/PDE/Limiter.cpp#L2786)):*
> ```cpp
> // *****************************************************************************
> {
>   const auto ndof = g_inputdeck.get< tag::discr, tag::ndof >();
> ```

I doubt we need `ndof` right now in this function.
If DG, then `rdof = ndof`. If `p0p1`, all the things required here is `rdof`.
___
*[`src/PDE/Limiter.cpp` line 2821 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/552#-N52YCLr9nuxh8TWGe03:-N52YCLr9nuxh8TWGe04:b6g0u2d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dd5118d3ea194918a3ed8dfb1cf0997b3756805f/src/PDE/Limiter.cpp#L2821)):*
> ```cpp
> 
>       // Evaluate the solution at quadrature point
>       auto U = tk::eval_state( ncomp, 0, rdof, ndof, e, unk,  B,
> ```

I think for the `eval_state` function, it should be
`
auto U = tk::eval_state( ncomp, 0, rdof, rdof, e, unk,  B, {0, ncomp-1} );
`
The first rdof actually is the maximum dof used to track the solution. The second one is ndof for its local element. If p0p1, it should evaluate p1 solution. So second dof argument should also be `rdof`.
Let me know if this makes sense to you.


<!-- Sent from Reviewable.io -->

2022-06-21 16:07 UTC, adityakpandare reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/552)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[`src/PDE/Limiter.cpp` line 2786 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/552#-N52ZQyBAMgo51lInoov:-N5606X71sqcBefyMmnx:b-k614gu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dd5118d3ea194918a3ed8dfb1cf0997b3756805f/src/PDE/Limiter.cpp#L2786)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I doubt we need `ndof` right now in this function.
If DG, then `rdof = ndof`. If `p0p1`, all the things required here is `rdof`.
</blockquote></details>

Yes, thanks!
___
*[`src/PDE/Limiter.cpp` line 2821 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/552#-N52YCLr9nuxh8TWGe03:-N560-ukECNoQom_1KX-:bujj84q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dd5118d3ea194918a3ed8dfb1cf0997b3756805f/src/PDE/Limiter.cpp#L2821)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I think for the `eval_state` function, it should be
`
auto U = tk::eval_state( ncomp, 0, rdof, rdof, e, unk,  B, {0, ncomp-1} );
`
The first rdof actually is the maximum dof used to track the solution. The second one is ndof for its local element. If p0p1, it should evaluate p1 solution. So second dof argument should also be `rdof`.
Let me know if this makes sense to you.
</blockquote></details>

Good catch! Yes, that makes sense, I'll make the change. Thanks!


<!-- Sent from Reviewable.io -->

2022-06-21 19:14 UTC, WeizhaoLi2018 approved these changes
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/552)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)



<!-- Sent from Reviewable.io -->

2022-06-21 20:15 UTC, merged