Add variable specific heat functionality for multispeciesTpg rebase
quinoacomputing/quinoa pull request #631
Opened 2024-11-19 22:48 UTC by madpeck3

New species section in the input deck used when the eos (in the materials section) is set to "thermallyperfectgas." The parameters necessary for specifying different thermodynamic properties for each species are set in the new species section.

Regression test added is the multispecies sod problem using the "thermallyperfectgas" eos.

2024-12-03 16:33 UTC, adityakpandare requested changes
Great work, @madpeck3! I have some comments, but otherwise looks good!

> Reviewed 16 of 63 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-:-ODCM_Vm2mG7wa6xa606:b-16sqni)* status: 16 of 63 files reviewed, 6 unresolved discussions (waiting on @madpeck3)

___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 149 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCM1vK2kyCuWKRsfTG:-ODCM1vK2kyCuWKRsfTH:btxicxp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L149)):*
> ```cpp
> 
>   tk::real temp = pr / (rho * R);
>   tk::real e = R * (-m_cp_coeff[0] * pow(temp, -1) +
> ```

Let's use the `std::pow` function instead. The std library pow function is type-safe. Let's do that for all `pow` functions in this class.
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 150 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCMMmJ6Q4vYF5tk8Dt:-ODCMMmJ6Q4vYF5tk8Du:b-j5l4tk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L150)):*
> ```cpp
>   tk::real temp = pr / (rho * R);
>   tk::real e = R * (-m_cp_coeff[0] * pow(temp, -1) +
>       m_cp_coeff[1] * log(temp) + (m_cp_coeff[2] - 1) * temp +
> ```

Same for `log`- let's use `std::log` instead.
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 187 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCLTMhDve_v58Bu1d-:-ODCLTMhDve_v58Bu1d0:b6w9d8a) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L187)):*
> ```cpp
>   tk::real tol = 1e-8; // Stopping condition
>   tk::real err = 1e8;
>   while (err > tol) {
> ```

This can be dangerous. Let's replace this with a for-loop instead with a fixed number of iterations (see `JWL::bisection`).
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 204 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCLnMHAJSlifQyMGZ2:-ODCLnMHAJSlifQyMGZ3:buqwdba) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L204)):*
> ```cpp
>       if (k == 2) fp_T += -1;
>       power += 1;
>     }
> ```

What root-finder is this? Could you mention that in a comment?
___
*[`tests/regression/inciter/multispecies/SodShocktube/sod_shocktube_p0p1.lua` line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCKH651IQl5FO5pqjO:-ODCKH651IQl5FO5pqjP:b-c4wr4b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/tests/regression/inciter/multispecies/SodShocktube/sod_shocktube_p0p1.lua#L76)):*
> ```Lua
>       "z-velocity"
>     },
>     elemalias = {
> ```

I suggest not using the 'elemalias' capability, since it will be deprecated soon. When that's done, the regression test baselines will have to be updated with the variables names in the 'elemvar'. Instead, let's remove the elemalias, and use only the elemvar right now.
___
*[`tests/regression/inciter/multispecies/SodShocktube/exodiff_dg.cfg` line 11 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCKpnR6Xu1mP6YTJB9:-ODCKpnR6Xu1mP6YTJBA:bk3rqzl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/tests/regression/inciter/multispecies/SodShocktube/exodiff_dg.cfg#L11)):*
> ```INI
> 	x-velocity_numerical
> 	y-velocity_numerical
> 	z-velocity_numerical
> ```

All these variable names will have to be updated once you remove the elemalias vector in the control files, for the regression tests to pass.


<!-- Sent from Reviewable.io -->

2024-12-11 15:58 UTC, madpeck3 commented on src/PDE/EoS/ThermallyPerfectGas.cpp
> +  while (i < maxiter) {
Added this based on `JWL::Bisection`

2024-12-11 15:59 UTC, madpeck3 commented on src/PDE/EoS/ThermallyPerfectGas.cpp
> +    }
Also added based on `JWL::Bisection`

2024-12-11 16:00 UTC, madpeck3 commented
The changes pushed should address all the comments by @adityakpandare

2024-12-11 16:19 UTC, adityakpandare approved these changes
Thanks, @madpeck3. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 47 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-:-ODqW04ZAc9YZVf-mqi-:b-vyembi)* status: 16 of 63 files reviewed, 8 unresolved discussions (waiting on @madpeck3)



<!-- Sent from Reviewable.io -->

2024-12-11 20:25 UTC, madpeck3 reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/631)* status: 16 of 63 files reviewed, 6 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 149 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCM1vK2kyCuWKRsfTG:-ODrOLzQ5muhOAk_04CA:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L149)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's use the `std::pow` function instead. The std library pow function is type-safe. Let's do that for all `pow` functions in this class.
</blockquote></details>

Done.
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 150 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCMMmJ6Q4vYF5tk8Dt:-ODrOMFa0Pxi95iG63eq:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L150)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same for `log`- let's use `std::log` instead.
</blockquote></details>

Done.
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 187 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCLTMhDve_v58Bu1d-:-ODrOMhG1ZJk0nAJ-QFU:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L187)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This can be dangerous. Let's replace this with a for-loop instead with a fixed number of iterations (see `JWL::bisection`).
</blockquote></details>

Done.
___
*[`src/PDE/EoS/ThermallyPerfectGas.cpp` line 204 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCLnMHAJSlifQyMGZ2:-ODrON4C21GcAftFwJPf:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/src/PDE/EoS/ThermallyPerfectGas.cpp#L204)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

What root-finder is this? Could you mention that in a comment?
</blockquote></details>

Done.
___
*[`tests/regression/inciter/multispecies/SodShocktube/exodiff_dg.cfg` line 11 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCKpnR6Xu1mP6YTJB9:-ODrOOyQ9x3RD4IgWyC2:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/tests/regression/inciter/multispecies/SodShocktube/exodiff_dg.cfg#L11)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

All these variable names will have to be updated once you remove the elemalias vector in the control files, for the regression tests to pass.
</blockquote></details>

Done.
___
*[`tests/regression/inciter/multispecies/SodShocktube/sod_shocktube_p0p1.lua` line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-ODCKH651IQl5FO5pqjO:-ODrOQ0l2sMySYg_CoEa:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f886a9ad8bef872b00e270a22b46ecb63fd58184/tests/regression/inciter/multispecies/SodShocktube/sod_shocktube_p0p1.lua#L76)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I suggest not using the 'elemalias' capability, since it will be deprecated soon. When that's done, the regression test baselines will have to be updated with the variables names in the 'elemvar'. Instead, let's remove the elemalias, and use only the elemvar right now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-11 20:32 UTC, adityakpandare approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/631#-:-ODrQ7KN6aMxI6dJHWNL:bnfp4nl)* status: 16 of 63 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-11 22:27 UTC, adityakpandare approved these changes
> Reviewed 2 of 63 files at r1, 44 of 47 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @madpeck3)



<!-- Sent from Reviewable.io -->

2024-12-11 22:41 UTC, merged