Add inlet outlet bc
quinoacomputing/quinoa pull request #633
Opened 2024-12-05 17:28 UTC by g-rydquist

Add an inlet boundary condition that prescribes a velocity on a sideset. Pressure and density are set such that they have zero gradient. A couple of potential features are missing as of now:

1. Outlet BC has not been added.
2. There is only functionality to assign a single inlet block to all sidesets (the first one in the .lua file). The functionality to read and store multiple inlets is there, but I wasn't sure how to, in `BCFunctions::inlet()`, differentiate which sideset was associated with which inlet, so I just take the first one that gets stored. However, this inlet can be assigned to multiple sidesets.

A further note: instead of removing the loop over the `bclist::Keys` in the `MultiMat` constructor and looping manually, I removed `inlet` from the list and just read it manually.

2024-12-23 16:47 UTC, adityakpandare requested changes
Thank you @g-rydquist. The inlet BC parsing code looks good. I have a few comments on the BC enforcement itself. 

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-:-OEoPSjQ94vGdp0jkMcG:b1u88p)* status: all files reviewed, 12 unresolved discussions (waiting on @g-rydquist)

___
*[`src/Inciter/Transporter.cpp` line 484 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoIc_r-tk7pna25g1g:-OEoIc_r-tk7pna25g1h:bx2kpzk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Inciter/Transporter.cpp#L484)):*
> ```cpp
>   using bclist = ctr::bclist::Keys;
>   const auto& bcs = g_inputdeck.get< tag::bc >();
>   brigand::for_each< bclist >( UserBC( g_inputdeck, usedsets ) );
> ```

This `brigand::for_each` is neither for timedep nor inlet BCs. Let's move it above the comment, as it was before (undo the change of moving it under the comment). Same for the `bclist`.
___
*[`src/Inciter/Transporter.cpp` line 489 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoJ2d2EffzAjICarrR:-OEoJ2d2EffzAjICarrS:bvw3m3t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Inciter/Transporter.cpp#L489)):*
> ```cpp
>       for (auto i : b.get< tag::sideset >())
>         usedsets.insert(static_cast<int>(i));
>     }
> ```

Nice! I like this! At some point, I will attempt at moving all BC's to this framework.
___
*[`src/PDE/MultiMat/FVMultiMat.hpp` line 102 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoKqSd74AypbQD2rBQ:-OEoKqSd74AypbQD2rBR:b-ncs89u) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/FVMultiMat.hpp#L102)):*
> ```cpp
>             v.clear();
>             v.insert(v.end(), sideset.begin(), sideset.end());
>             m_bc.push_back( { v, inlet, noOpGrad } );
> ```

Is the `noOpGrad` correct for inlet? Shouldn't we be using velocity/temperature info from the BCs to get the grad? Or are we punting on it for now (which is okay; just making sure)?
___
*[`src/Control/Inciter/InputDeck/InputDeck.hpp` line 139 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoJDXl-fQfYyG0-5Te:-OEoJDXl-fQfYyG0-5Tf:b18k7s8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Control/Inciter/InputDeck/InputDeck.hpp#L139)):*
> ```cpp
>       tag::materialid,   std::size_t
>     > >
>   >,
> ```

Just to be a little "clear", let's move the `tag::inlet` to the very end, adjacent to `tag::timedep`, as a hint that inlet is treated similar to timedep.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 137 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoM0YM2ztFeJ2BexPc:-OEoM0YM2ztFeJ2BexPd:bopvvhn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L137)):*
> ```cpp
>     auto nmat = g_inputdeck.get< tag::multimat, tag::nmat >();
>     const auto& solidx = g_inputdeck.get< tag::matidxmap, tag::solidx >();
>     auto& inbc = g_inputdeck.get< tag::bc >()[0].get< tag::inlet >();
> ```

This index 0 corresponds to the mesh id. This indicates that for now, our MultiMat solver BCs aren't linked to the overset mesh solver.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 140 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoMISGDwhMflGkZjRQ:-OEoMISGDwhMflGkZjRR:b6k77hs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L140)):*
> ```cpp
> 
>     // inlet velocity and material
>     auto u_in = inbc[0].get< tag::velocity >();
> ```

This is where only the first entry of the `tag::inlet` vector is used. I see. This will need some reworking. Let's create an issue on github, pointing to this function, and mentioning that it is not compatible with multiple inlet-bcs.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 158 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoMmKs26BO16wS_ok6:-OEoMmKs26BO16wS_ok7:b-k57zp5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L158)):*
> ```cpp
>     auto v1r = 2.0*u_in[0] - v1l;
>     auto v2r = 2.0*u_in[1] - v2l;
>     auto v3r = 2.0*u_in[2] - v3l;
> ```

I'm not sure this vector algebra works out for an unstructured mesh an general velocity. Instead, the ghost-state velocity should be set to the inlet BC values. So basically, `v1r = u_in[0]` etc. This is what is called a "weak" BC enforcement that's typically used in FV/DG formulations.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 177 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoO3bc0JlFfAbzOaMo:-OEoO3bc0JlFfAbzOaMp:bqumvlz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L177)):*
> ```cpp
> 
>       // zero bulk pressure and density gradient
>       ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat, k)] * p;
> ```

This quantity is the material pressure, not the bulk pressure. So if you had different EOS for each material, this code is incorrect. If the inlet BC is supposed to be used for subsonic conditions, use the pressure from inside (one characteristic moving out from inside at subsonic conditions): 
```
ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat,k)] * ul[ncomp+pressureIdx(nmat,k)]/ul[volfracIdx(nmat,k)];
```

If the inlet BC is supposed to be used for supersonic conditions, we need to accept inlet PC pressure and use that as the pressure (all characteristics moving in at supersonic conditions):
```
ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat,k)] * p_in;
```
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 178 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoNhrL1Lp1jHPESycV:-OEoNhrL1Lp1jHPESycW:b-pkptsn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L178)):*
> ```cpp
>       // zero bulk pressure and density gradient
>       ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat, k)] * p;
>       ur[densityIdx(nmat,k)] = ur[volfracIdx(nmat,k)] * rho;
> ```

This quantity is the material density, not the bulk density. So if you had different EOS for each material, this code is incorrect. We need to use the EOS to compute material density based on the user-specified inlet BC temperature and appropriate pressure (based on sub or super sonic).
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 180 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoPEjKEn451QxBfJy5:-OEoPEjKEn451QxBfJy6:b537t5z) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L180)):*
> ```cpp
>       ur[densityIdx(nmat,k)] = ur[volfracIdx(nmat,k)] * rho;
>       ur[energyIdx(nmat,k)] = ur[volfracIdx(nmat,k)] *
>         mat_blk[k].compute< EOS::totalenergy >(rho, v1r, v2r, v3r, p);
> ```

Material density should be used here: `ur[densityIdx...]/ur[volfracIdx...]`.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 185 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoP9O_DSUB5932_PRm:-OEoP9O_DSUB5932_PRn:bvfgw9x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L185)):*
> ```cpp
>     ur[momentumIdx(nmat, 0)] = rho * v1r;
>     ur[momentumIdx(nmat, 1)] = rho * v2r;
>     ur[momentumIdx(nmat, 2)] = rho * v3r;
> ```

Bulk density rho needs to be recomputed once each material density is computed from EOS as commented above.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 108 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoKNzNDpH1HcPvAWfq:-OEoKNzNDpH1HcPvAWfr:b-4bj7ep [...]

2025-01-10 14:38 UTC, g-rydquist reviewed
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Control/Inciter/InputDeck/InputDeck.hpp` line 139 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoJDXl-fQfYyG0-5Te:-OGB8t7KDAyH2VlXS4vb:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Control/Inciter/InputDeck/InputDeck.hpp#L139)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Just to be a little "clear", let's move the `tag::inlet` to the very end, adjacent to `tag::timedep`, as a hint that inlet is treated similar to timedep.
</blockquote></details>

Done.
___
*[`src/Inciter/Transporter.cpp` line 484 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoIc_r-tk7pna25g1g:-OGB9PkcDpYhYAzCYwqb:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Inciter/Transporter.cpp#L484)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This `brigand::for_each` is neither for timedep nor inlet BCs. Let's move it above the comment, as it was before (undo the change of moving it under the comment). Same for the `bclist`.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 140 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoMISGDwhMflGkZjRQ:-OGBD4a6BN3x_4l3Xfuv:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L140)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is where only the first entry of the `tag::inlet` vector is used. I see. This will need some reworking. Let's create an issue on github, pointing to this function, and mentioning that it is not compatible with multiple inlet-bcs.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 158 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoMmKs26BO16wS_ok6:-OGAwgy111dKQJ5gHPDz:b-qdwor) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L158)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I'm not sure this vector algebra works out for an unstructured mesh an general velocity. Instead, the ghost-state velocity should be set to the inlet BC values. So basically, `v1r = u_in[0]` etc. This is what is called a "weak" BC enforcement that's typically used in FV/DG formulations.
</blockquote></details>

So I'd been thinking about this, and I'm not fully sure I'm following. I hadn't heard of weak enforcement of BC's, but after reading up on them, I get what's going on. However, I'm not exactly able to make the jump from including the Dirichlet BC's in the variational form to setting the ghost cells to them directly (unless I've been reading up on something different.) And then why are no-slip BC's calculated by "mirroring" the interior cell with the ghost cell, instead of setting the ghost cell directly to 0?
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 177 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoO3bc0JlFfAbzOaMo:-OGC8tQoAbhCGuWqdavt:buqps6g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L177)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This quantity is the material pressure, not the bulk pressure. So if you had different EOS for each material, this code is incorrect. If the inlet BC is supposed to be used for subsonic conditions, use the pressure from inside (one characteristic moving out from inside at subsonic conditions): 
```
ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat,k)] * ul[ncomp+pressureIdx(nmat,k)]/ul[volfracIdx(nmat,k)];
```

If the inlet BC is supposed to be used for supersonic conditions, we need to accept inlet PC pressure and use that as the pressure (all characteristics moving in at supersonic conditions):
```
ur[ncomp+pressureIdx(nmat, k)] = ur[volfracIdx(nmat,k)] * p_in;
```
</blockquote></details>

Sounds good. As I was putting these in, I realized we should also likely have some error checking for if the user puts in a velocity that is flowing out as well...
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 178 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoNhrL1Lp1jHPESycV:-OGCFPXbDb8GMyJgIi-8:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L178)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This quantity is the material density, not the bulk density. So if you had different EOS for each material, this code is incorrect. We need to use the EOS to compute material density based on the user-specified inlet BC temperature and appropriate pressure (based on sub or super sonic).
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 180 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoPEjKEn451QxBfJy5:-OGCFQw0AWaIJ9K4APKe:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L180)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Material density should be used here: `ur[densityIdx...]/ur[volfracIdx...]`.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 185 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoP9O_DSUB5932_PRm:-OGCFSBkB8HFChObHYYL:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L185)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Bulk density rho needs to be recomputed once each material density is computed from EOS as commented above.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 108 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoKNzNDpH1HcPvAWfq:-OGBy4oj89_QysnmrOEb:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/DGMultiMat.hpp#L108)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This function repeats in all fv/dg implementations. Let's move it outside to DGPDE.cpp and have everyone call that function.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/FVMultiMat.hpp` line 102 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoKqSd74AypbQD2rBQ:-OGBNnpGBv5cQPZl4tHA:b-eyiixa) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/FVMultiMat.hpp#L102)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is the `noOpGrad` correct for inlet? Shouldn't we be using velocity/temperature info from the BCs to get the grad? Or are we punting on it for now (which is okay; just making sure)?
</blockquote></details>

Yes, I suppose it should be. This was an oversight on my part, and I'll think on it a bit more and add it in a later commit.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 273 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OGCCEB-1GSsA4wrGY0y:-OGCCEB0-fCxf6wFRvc1:b-sqgmk8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L273)):*
> ```cpp
> 
>         // material pr [...]

2025-02-10 20:19 UTC, g-rydquist reviewed
Hey @adityakpandare, thanks again for looking at this and sorry for taking so long. I think it should be ready for review now!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-:-OIlVdmFEuFb1_REsO9H:bydu99x)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Inciter/Transporter.cpp` line 489 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoJ2d2EffzAjICarrR:-OIlUmWo6-EtJ7jWQ3c0:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/Inciter/Transporter.cpp#L489)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice! I like this! At some point, I will attempt at moving all BC's to this framework.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 137 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoM0YM2ztFeJ2BexPc:-OIlVP03-TcWFpCUoSNY:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L137)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This index 0 corresponds to the mesh id. This indicates that for now, our MultiMat solver BCs aren't linked to the overset mesh solver.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 158 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoMmKs26BO16wS_ok6:-OIlVGPA0jgW78FBKVnr:b6e1m01) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L158)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

So I'd been thinking about this, and I'm not fully sure I'm following. I hadn't heard of weak enforcement of BC's, but after reading up on them, I get what's going on. However, I'm not exactly able to make the jump from including the Dirichlet BC's in the variational form to setting the ghost cells to them directly (unless I've been reading up on something different.) And then why are no-slip BC's calculated by "mirroring" the interior cell with the ghost cell, instead of setting the ghost cell directly to 0?
</blockquote></details>

I think this was cleared up from out email conversation.


<!-- Sent from Reviewable.io -->

2025-02-11 23:57 UTC, adityakpandare approved these changes
Excellent work, @g-rydquist! Looks good, I just have a couple of questions.

> Reviewed 5 of 9 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-:-OIrRO0GBJLHnJ5VbFW7:brh2zf)* status: all files reviewed, 2 unresolved discussions (waiting on @g-rydquist)

___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 177 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoO3bc0JlFfAbzOaMo:-OIrPj2R62d8OWCL76kx:b1vvq8z) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L177)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Sounds good. As I was putting these in, I realized we should also likely have some error checking for if the user puts in a velocity that is flowing out as well...
</blockquote></details>

Yes, let's leave that for later maybe?
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 273 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OGCCEB-1GSsA4wrGY0y:-OIrQIMq8JN5EcNYzmVZ:b-tr8q8n) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L273)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Based on the discussion above, this is technically incorrect, no? We should be using the volume fraction of the exterior cell, as follows, correct?
</blockquote></details>

Nice catch! Yes, this is a bug. It should be using the volfrac from `ur`, not `ul`. Would you fix it, or should I on a separate branch?
___
*[`src/PDE/MultiMat/FVMultiMat.hpp` line 102 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoKqSd74AypbQD2rBQ:-OIrQvFaErMSoDq2hAMD:b-9nvnzx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/FVMultiMat.hpp#L102)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Yes, I suppose it should be. This was an oversight on my part, and I'll think on it a bit more and add it in a later commit.
</blockquote></details>

Zero gradients (the current implementation) is correct.
___
*[`src/Control/Inciter/InputDeck/LuaParser.cpp` line 1109 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OIrNrZw7VT9Ene0tInk:-OIrNrZw7VT9Ene0tInl:by3dfh3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/349ae2d5fd6873f0e89ff15be53d20dce4b9b19d/src/Control/Inciter/InputDeck/LuaParser.cpp#L1109)):*
> ```cpp
>           storeIfSpecd< tk::real >(sol_inbc[j+1], "temperature",
>             inbc_deck[j].get< tag::temperature >(), 0.0);
>             
> ```

Could you remove this whitespace?
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 301 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OIrQfGY0MwS6EpFI3Gf:-OIrQfGY0MwS6EpFI3Gg:b-tb53my) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L301)):*
> ```cpp
> 
>         // material pressures
>         ur[ncomp+pressureIdx(nmat, k)] = ul[volfracIdx(nmat, k)] * p;
> ```

The same bug repeats here as well. This needs to be corrected too.


<!-- Sent from Reviewable.io -->

2025-02-12 14:57 UTC, g-rydquist reviewed
Sounds good, thanks @adityakpandare. I've fixed that formatting issue and the bugs you pointed out, and I think we should be set. I also opened an issue on GitHub for checking that the inlet is flowing into the domain. If you think it's ready I'll go ahead and merge it in!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-:-OIu_aXq24LwDTVuntbi:bh5xcl0)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[`src/Control/Inciter/InputDeck/LuaParser.cpp` line 1109 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OIrNrZw7VT9Ene0tInk:-OIudiqI9rVGLSXVf9DA:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/349ae2d5fd6873f0e89ff15be53d20dce4b9b19d/src/Control/Inciter/InputDeck/LuaParser.cpp#L1109)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you remove this whitespace?
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 177 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OEoO3bc0JlFfAbzOaMo:-OIudp_rCXLqZ9LlH94l:b9hwors) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L177)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yes, let's leave that for later maybe?
</blockquote></details>

Added an issue on GitHub for this.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 273 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OGCCEB-1GSsA4wrGY0y:-OIudw5F-5Kw6Am6bl1H:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L273)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice catch! Yes, this is a bug. It should be using the volfrac from `ur`, not `ul`. Would you fix it, or should I on a separate branch?
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 301 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OIrQfGY0MwS6EpFI3Gf:-OIue-jr2U8Q_-boZfge:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L301)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The same bug repeats here as well. This needs to be corrected too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-12 16:39 UTC, adityakpandare approved these changes
Good to merge. Thanks!
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-:-OIv0mm41wEt7FArQ9au:b-6zwatn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @g-rydquist)

___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 273 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/633#-OGCCEB-1GSsA4wrGY0y:-OIv0cew-uEDfYZ7Vdv9:b-9755fn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/315eecf6ee1f721ca30d5039802dcbb2f383b09f/src/PDE/MultiMat/BCFunctions.hpp#L273)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2025-02-12 17:13 UTC, merged